(function () {
  const catalog = window.AI_CATALOG;
  if (!catalog || !Array.isArray(catalog.tools)) {
    return;
  }

  function formatTrafficLabel(monthlyVisits) {
    if (monthlyVisits >= 1000000000) {
      return `${(monthlyVisits / 1000000000).toFixed(1)}B monthly visits`;
    }
    return `${(monthlyVisits / 1000000).toFixed(1)}M monthly visits`;
  }

  const extraTools = [
    { id: "lavender", name: "Lavender", vendor: "Lavender", logoLetter: "L", accent: "linear-gradient(145deg, #8b5cf6, #06b6d4)", url: "https://www.lavender.ai/", summary: "An AI email coach built around helping sales reps write more effective outbound messages.", categories: ["Sales", "Writing"], audience: ["Sales reps", "SDRs", "Revenue teams"], pricing: "Freemium", monthlyVisits: 2900000, recommendation: "Useful for focused buyers who want email coaching rather than a broad sales platform.", searchTerms: ["email coach ai", "sales email ai"] },
    { id: "regieai", name: "Regie.ai", vendor: "Regie.ai", logoLetter: "R", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://www.regie.ai/", summary: "A sales content and prospecting platform built around AI-assisted messaging and outbound coordination.", categories: ["Sales", "Writing", "Automation"], audience: ["Sales teams", "Revenue leaders", "GTM operators"], pricing: "Paid", monthlyVisits: 2400000, recommendation: "A strong B2B inclusion for teams comparing sales-specific AI content systems.", searchTerms: ["sales messaging ai", "prospecting ai"] },
    { id: "peopleai", name: "People.ai", vendor: "People.ai", logoLetter: "P", accent: "linear-gradient(145deg, #111827, #14b8a6)", url: "https://www.people.ai/", summary: "A revenue operations platform that uses AI and data capture to improve pipeline visibility and execution.", categories: ["Sales", "Automation", "Productivity"], audience: ["Revenue ops", "Sales leaders", "Enterprise teams"], pricing: "Paid", monthlyVisits: 2200000, recommendation: "Relevant for larger revenue organizations evaluating AI beyond lightweight outreach tooling.", searchTerms: ["revenue ops ai", "pipeline ai"] },
    { id: "intercomfin", name: "Intercom Fin", vendor: "Intercom", logoLetter: "F", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.intercom.com/fin", summary: "An AI support agent product for help center, ticket deflection, and customer service automation.", categories: ["Automation", "Sales", "Assistants"], audience: ["Support teams", "Customer success", "SaaS companies"], pricing: "Paid", monthlyVisits: 4300000, recommendation: "A high-signal addition for support leaders comparing serious AI agent products.", searchTerms: ["customer support ai", "support agent ai", "fin ai"] },
    { id: "ada", name: "Ada", vendor: "Ada", logoLetter: "A", accent: "linear-gradient(145deg, #06b6d4, #1d4ed8)", url: "https://www.ada.cx/", summary: "A customer service automation platform built around AI support conversations and workflow routing.", categories: ["Automation", "Sales", "Assistants"], audience: ["Support teams", "E-commerce teams", "Enterprises"], pricing: "Paid", monthlyVisits: 3200000, recommendation: "Useful to include because support automation buyers often evaluate Ada alongside Intercom and others.", searchTerms: ["support automation ai", "customer service bot"] },
    { id: "tidio", name: "Tidio AI", vendor: "Tidio", logoLetter: "T", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.tidio.com/ai/", summary: "A chat and support platform for SMB websites using AI to assist conversations and lead capture.", categories: ["Sales", "Automation", "Assistants"], audience: ["Small businesses", "E-commerce teams", "Support teams"], pricing: "Freemium", monthlyVisits: 9700000, recommendation: "A sensible addition because smaller teams often want website chat AI with quick setup.", searchTerms: ["chatbot ai", "website support ai"] },
    { id: "manychat", name: "Manychat", vendor: "Manychat", logoLetter: "M", accent: "linear-gradient(145deg, #22c55e, #16a34a)", url: "https://manychat.com/", summary: "A messaging automation platform popular for Instagram, WhatsApp, and DM-based lead generation.", categories: ["Sales", "Automation"], audience: ["Creators", "E-commerce brands", "Agencies"], pricing: "Freemium", monthlyVisits: 13100000, recommendation: "Included because messaging-led commerce and creator funnels remain a durable AI-adjacent buying path.", searchTerms: ["instagram automation", "dm automation", "chat marketing ai"] },
    { id: "voiceflow", name: "Voiceflow", vendor: "Voiceflow", logoLetter: "V", accent: "linear-gradient(145deg, #0f172a, #7c3aed)", url: "https://www.voiceflow.com/", summary: "A conversation design platform for teams building AI chatbots, agents, and voice interfaces.", categories: ["Automation", "Assistants", "Coding"], audience: ["Product teams", "Support teams", "Developers"], pricing: "Freemium", monthlyVisits: 5900000, recommendation: "A strong fit when the buyer wants to design agent experiences rather than only consume them.", searchTerms: ["chatbot builder", "agent design", "conversation design"] },
    { id: "dify", name: "Dify", vendor: "Dify", logoLetter: "D", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://dify.ai/", summary: "An AI app and workflow platform for building internal tools, assistants, and agent experiences.", categories: ["Automation", "Coding", "Assistants"], audience: ["Developers", "Ops teams", "Startups"], pricing: "Free / Paid", monthlyVisits: 7500000, recommendation: "A notable builder-platform listing for teams experimenting with custom internal AI apps.", searchTerms: ["llm app builder", "ai workflow builder"] },
    { id: "flowise", name: "Flowise", vendor: "Flowise", logoLetter: "F", accent: "linear-gradient(145deg, #0ea5e9, #22c55e)", url: "https://flowiseai.com/", summary: "A visual builder for LLM workflows, RAG systems, and agent orchestration with a strong developer audience.", categories: ["Automation", "Coding"], audience: ["Developers", "Prototype teams", "Power users"], pricing: "Free / Paid", monthlyVisits: 2800000, recommendation: "A high-signal addition for users who want flow-based orchestration rather than a general chat app.", searchTerms: ["rag builder", "llm workflow", "agent orchestration"] },
    { id: "stackai", name: "Stack AI", vendor: "Stack AI", logoLetter: "S", accent: "linear-gradient(145deg, #111827, #2563eb)", url: "https://www.stack-ai.com/", summary: "An AI workflow platform for internal assistants, retrieval apps, and business automation projects.", categories: ["Automation", "Coding", "Assistants"], audience: ["Operations teams", "Developers", "Enterprises"], pricing: "Paid", monthlyVisits: 2000000, recommendation: "Useful to include for teams shopping no-code or low-code agent infrastructure.", searchTerms: ["ai workflow platform", "internal ai apps"] },
    { id: "synthflow", name: "Synthflow", vendor: "Synthflow", logoLetter: "S", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://synthflow.ai/", summary: "A voice-agent platform focused on phone automation, inbound handling, and operational call workflows.", categories: ["Automation", "Audio", "Sales"], audience: ["Operations teams", "Support teams", "Sales teams"], pricing: "Paid", monthlyVisits: 3300000, recommendation: "A strong niche addition because voice agents are becoming a real operational buying category.", searchTerms: ["voice agent", "phone ai", "call automation"] },
    { id: "vapi", name: "Vapi", vendor: "Vapi", logoLetter: "V", accent: "linear-gradient(145deg, #111827, #06b6d4)", url: "https://vapi.ai/", summary: "A developer-first platform for building voice agents, phone systems, and real-time AI call experiences.", categories: ["Automation", "Audio", "Coding"], audience: ["Developers", "Startups", "Voice teams"], pricing: "Paid", monthlyVisits: 4200000, recommendation: "A high-signal builder option for technical teams working on real-time voice products.", searchTerms: ["voice api", "telephony ai", "phone agent api"] },
    { id: "retellai", name: "Retell AI", vendor: "Retell AI", logoLetter: "R", accent: "linear-gradient(145deg, #2563eb, #0f172a)", url: "https://www.retellai.com/", summary: "A voice AI platform for conversational phone agents and real-time customer interactions.", categories: ["Automation", "Audio", "Sales"], audience: ["Developers", "Support teams", "Voice teams"], pricing: "Paid", monthlyVisits: 3000000, recommendation: "Relevant for teams comparing the fast-growing set of voice-agent infrastructure vendors.", searchTerms: ["retell ai", "voice assistant api", "call center ai"] },
    { id: "hedra", name: "Hedra", vendor: "Hedra", logoLetter: "H", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://www.hedra.com/", summary: "An AI character and talking-video platform for expressive avatar content and social storytelling.", categories: ["Video", "Audio", "Design"], audience: ["Creators", "Social teams", "Agencies"], pricing: "Freemium", monthlyVisits: 9600000, recommendation: "A strong addition for creators exploring the newer wave of expressive character video tools.", searchTerms: ["avatar video ai", "talking character ai"] },
    { id: "haiper", name: "Haiper", vendor: "Haiper", logoLetter: "H", accent: "linear-gradient(145deg, #0ea5e9, #7c3aed)", url: "https://haiper.ai/", summary: "A generative video tool for text-to-video and image-to-video experimentation with a consumer-friendly interface.", categories: ["Video", "Design"], audience: ["Creators", "Designers", "Social teams"], pricing: "Free / Paid", monthlyVisits: 7700000, recommendation: "Useful when buyers want lightweight generative video exploration without a heavy editing workflow.", searchTerms: ["text to video ai", "image to video ai"] },
    { id: "klingai", name: "Kling AI", vendor: "Kuaishou", logoLetter: "K", accent: "linear-gradient(145deg, #111827, #2563eb)", url: "https://klingai.com/", summary: "A high-interest generative video product for cinematic motion, image animation, and prompt-driven video creation.", categories: ["Video", "Design"], audience: ["Creators", "Designers", "Studios"], pricing: "Free / Paid", monthlyVisits: 28800000, recommendation: "A high-signal listing because global buyers increasingly search specifically for next-wave video generators.", searchTerms: ["kling", "video generation ai", "cinematic ai video"] },
    { id: "hailuoai", name: "Hailuo AI", vendor: "MiniMax", logoLetter: "H", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://hailuoai.video/", summary: "A generative video platform gaining attention for consumer-friendly text-to-video creation and motion clips.", categories: ["Video", "Design"], audience: ["Creators", "Social teams", "Designers"], pricing: "Free / Paid", monthlyVisits: 18900000, recommendation: "Worth comparing when buyers are looking beyond first-wave AI video tools.", searchTerms: ["hailuo", "minimax video", "ai video generator"] },
    { id: "dreamina", name: "Dreamina", vendor: "ByteDance", logoLetter: "D", accent: "linear-gradient(145deg, #7c3aed, #ec4899)", url: "https://dreamina.capcut.com/", summary: "A generative image and creative ideation product tied to ByteDance's consumer creation ecosystem.", categories: ["Design", "Video"], audience: ["Creators", "Designers", "Social teams"], pricing: "Free / Paid", monthlyVisits: 15400000, recommendation: "A useful addition for buyers who want image generation near their short-form creation workflow.", searchTerms: ["dreamina ai", "image generation", "capcut ai"] },
    { id: "tensorart", name: "Tensor.Art", vendor: "Tensor.Art", logoLetter: "T", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://tensor.art/", summary: "A community-oriented image generation platform for models, prompts, and creative experimentation.", categories: ["Design"], audience: ["Creators", "Designers", "AI art users"], pricing: "Freemium", monthlyVisits: 12200000, recommendation: "Good to include because community model hubs remain a meaningful image-generation buying route.", searchTerms: ["ai art", "model hub", "image prompts"] },
    { id: "seaart", name: "SeaArt", vendor: "SeaArt", logoLetter: "S", accent: "linear-gradient(145deg, #0ea5e9, #22c55e)", url: "https://www.seaart.ai/", summary: "A high-volume AI art platform with templates, community content, and consumer-friendly generation flows.", categories: ["Design"], audience: ["Creators", "Designers", "Consumers"], pricing: "Freemium", monthlyVisits: 26700000, recommendation: "A strong listing for users who want a faster, template-heavy creative image experience.", searchTerms: ["sea art ai", "ai art generator"] },
    { id: "mage", name: "Mage", vendor: "Mage", logoLetter: "M", accent: "linear-gradient(145deg, #111827, #ec4899)", url: "https://www.mage.space/", summary: "A browser-based AI image creation tool geared toward simple prompt-driven visual generation.", categories: ["Design"], audience: ["Creators", "Designers", "Students"], pricing: "Freemium", monthlyVisits: 3100000, recommendation: "A practical long-tail inclusion because users still search for lightweight image generators by name.", searchTerms: ["mage space", "image ai", "prompt art"] },
    { id: "getimg", name: "getimg.ai", vendor: "getimg.ai", logoLetter: "G", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://getimg.ai/", summary: "A generation and editing platform for images, inpainting, model options, and fast creative iteration.", categories: ["Design"], audience: ["Designers", "Creators", "Marketers"], pricing: "Freemium", monthlyVisits: 8400000, recommendation: "A strong comparison option when buyers want image generation plus practical editing controls.", searchTerms: ["get img", "inpainting ai", "image editor ai"] },
    { id: "artbreeder", name: "Artbreeder", vendor: "Artbreeder", logoLetter: "A", accent: "linear-gradient(145deg, #8b5cf6, #ec4899)", url: "https://www.artbreeder.com/", summary: "A creative image platform known for remixing, blending, and iterative visual exploration.", categories: ["Design"], audience: ["Artists", "Designers", "Creators"], pricing: "Freemium", monthlyVisits: 5400000, recommendation: "A good inclusion for users who value exploration and remixing more than one-shot prompt generation.", searchTerms: ["art breeder", "image remix ai"] },
    { id: "scenario", name: "Scenario", vendor: "Scenario", logoLetter: "S", accent: "linear-gradient(145deg, #0f172a, #8b5cf6)", url: "https://www.scenario.com/", summary: "An AI image workflow platform for game, asset, and brand-consistent visual generation.", categories: ["Design"], audience: ["Game teams", "Design teams", "Studios"], pricing: "Paid", monthlyVisits: 3300000, recommendation: "Relevant for teams that care about controllable asset pipelines rather than consumer art tools.", searchTerms: ["game asset ai", "brand image generation"] }
  ].map((tool) => ({
    ...tool,
    trafficLabel: formatTrafficLabel(tool.monthlyVisits),
    sources: {
      futurepedia: "https://www.futurepedia.io/ai-tools",
      toolify: "https://www.toolify.ai/Best-trending-AI-Tools"
    }
  }));

  const existingIds = new Set(catalog.tools.map((tool) => tool.id));
  extraTools.forEach((tool) => {
    if (!existingIds.has(tool.id)) {
      catalog.tools.push(tool);
      existingIds.add(tool.id);
    }
  });
}());
