window.AI_CATALOG.tools.push(
  {
    id: "canva",
    name: "Canva",
    vendor: "Canva",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #06b6d4, #3b82f6)",
    url: "https://www.canva.com/",
    summary: "A mainstream creative workspace that now blends design, presentations, brand kits, and AI generation into one accessible surface.",
    categories: ["Design", "Productivity", "Writing"],
    audience: ["Marketers", "Creators", "Small teams", "Agencies"],
    pricing: "Freemium",
    monthlyVisits: 250000000,
    trafficLabel: "250.0M monthly visits",
    recommendation: "One of the safest default picks if you need broad creative output without assembling a fragmented stack.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "jasper",
    name: "Jasper",
    vendor: "Jasper",
    logoLetter: "J",
    accent: "linear-gradient(145deg, #7c3aed, #2563eb)",
    url: "https://www.jasper.ai/",
    summary: "A marketing-focused AI writing workspace tuned for campaign production, brand control, and content operations.",
    categories: ["Writing", "Sales", "Productivity"],
    audience: ["Marketing teams", "Content ops", "Agencies"],
    pricing: "Paid",
    monthlyVisits: 5200000,
    trafficLabel: "5.2M monthly visits",
    recommendation: "Most relevant when your team cares more about controlled brand output than general-purpose chat behavior.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "copyai",
    name: "Copy.ai",
    vendor: "Copy.ai",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #111827, #8b5cf6)",
    url: "https://www.copy.ai/",
    summary: "A GTM-oriented AI platform positioned around sales content, outbound workflows, and process automation for revenue teams.",
    categories: ["Writing", "Sales", "Automation"],
    audience: ["Sales teams", "Growth teams", "Revenue ops"],
    pricing: "Freemium",
    monthlyVisits: 8100000,
    trafficLabel: "8.1M monthly visits",
    recommendation: "A strong option if you want AI to sit closer to pipeline workflows than a generic writing assistant would.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "leonardo",
    name: "Leonardo AI",
    vendor: "Leonardo",
    logoLetter: "L",
    accent: "linear-gradient(145deg, #0f172a, #9333ea)",
    url: "https://leonardo.ai/",
    summary: "A visual generation platform favored for game assets, concept art, styled imagery, and higher-control creative exploration.",
    categories: ["Design"],
    audience: ["Designers", "Game teams", "Creative generalists"],
    pricing: "Freemium",
    monthlyVisits: 18300000,
    trafficLabel: "18.3M monthly visits",
    recommendation: "A solid Midjourney comparison if you want more generation knobs and asset-style experimentation.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "pika",
    name: "Pika",
    vendor: "Pika",
    logoLetter: "P",
    accent: "linear-gradient(145deg, #ec4899, #8b5cf6)",
    url: "https://pika.art/",
    summary: "A fast-moving AI video product focused on short-form generation, playful edits, and creator-friendly motion workflows.",
    categories: ["Video", "Design"],
    audience: ["Creators", "Social teams", "Video experimenters"],
    pricing: "Freemium",
    monthlyVisits: 7300000,
    trafficLabel: "7.3M monthly visits",
    recommendation: "Most relevant when speed, stylistic range, and social-friendly iteration matter more than enterprise governance.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "invideo",
    name: "InVideo AI",
    vendor: "InVideo",
    logoLetter: "I",
    accent: "linear-gradient(145deg, #0ea5e9, #2563eb)",
    url: "https://invideo.io/",
    summary: "A high-traction AI video builder for converting ideas, scripts, and marketing angles into quick video outputs.",
    categories: ["Video", "Writing"],
    audience: ["Marketers", "Creators", "Small businesses"],
    pricing: "Freemium",
    monthlyVisits: 12100000,
    trafficLabel: "12.1M monthly visits",
    recommendation: "A useful pick when your workflow starts from marketing copy and needs to end in publishable video fast.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "descript",
    name: "Descript",
    vendor: "Descript",
    logoLetter: "D",
    accent: "linear-gradient(145deg, #111827, #14b8a6)",
    url: "https://www.descript.com/",
    summary: "An editing workspace for audio and video teams that want transcript-native workflows, overdubs, and cleaner collaborative editing.",
    categories: ["Audio", "Video", "Writing"],
    audience: ["Podcasters", "Media teams", "Marketers"],
    pricing: "Freemium",
    monthlyVisits: 4700000,
    trafficLabel: "4.7M monthly visits",
    recommendation: "A strong operational choice when transcript-led editing is more important than flashy generation demos.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "murf",
    name: "Murf",
    vendor: "Murf",
    logoLetter: "M",
    accent: "linear-gradient(145deg, #f97316, #ef4444)",
    url: "https://murf.ai/",
    summary: "A practical voice generation platform for narration, explainers, internal content, and marketing voiceovers.",
    categories: ["Audio", "Video"],
    audience: ["Marketers", "L&D teams", "Agencies"],
    pricing: "Freemium",
    monthlyVisits: 3300000,
    trafficLabel: "3.3M monthly visits",
    recommendation: "Worth using when you need polished business voiceovers without building a bespoke speech stack.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "luma",
    name: "Luma AI",
    vendor: "Luma",
    logoLetter: "L",
    accent: "linear-gradient(145deg, #111827, #06b6d4)",
    url: "https://lumalabs.ai/",
    summary: "A generative video and 3D-forward product that stands out for cinematic visuals and scene generation workflows.",
    categories: ["Video", "Design"],
    audience: ["Creative studios", "Filmmakers", "Design teams"],
    pricing: "Freemium",
    monthlyVisits: 10400000,
    trafficLabel: "10.4M monthly visits",
    recommendation: "A strong fit when your team wants more cinematic output and visual ambition than template-first video tools provide.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "openart",
    name: "OpenArt",
    vendor: "OpenArt",
    logoLetter: "O",
    accent: "linear-gradient(145deg, #7c3aed, #06b6d4)",
    url: "https://openart.ai/",
    summary: "A creator-facing image platform for generating, editing, and iterating on artwork with broad model variety.",
    categories: ["Design"],
    audience: ["Creators", "Designers", "Art teams"],
    pricing: "Freemium",
    monthlyVisits: 9200000,
    trafficLabel: "9.2M monthly visits",
    recommendation: "Best when you want a wider creative playground and model variety without leaving a browser workflow.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "clipchamp",
    name: "Clipchamp",
    vendor: "Microsoft",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #2563eb, #14b8a6)",
    url: "https://clipchamp.com/",
    summary: "A mainstream browser video editor with AI assist features that fits business users already inside the Microsoft ecosystem.",
    categories: ["Video", "Productivity"],
    audience: ["Business teams", "Educators", "Creators"],
    pricing: "Freemium",
    monthlyVisits: 25100000,
    trafficLabel: "25.1M monthly visits",
    recommendation: "A sensible default when your team wants accessible editing with less workflow change than creative-specialist tools require.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "vidnoz",
    name: "Vidnoz",
    vendor: "Vidnoz",
    logoLetter: "V",
    accent: "linear-gradient(145deg, #2563eb, #8b5cf6)",
    url: "https://www.vidnoz.com/",
    summary: "An avatar and business video platform optimized for rapid explainer content, localized output, and sales-ready clips.",
    categories: ["Video", "Translation", "Sales"],
    audience: ["GTM teams", "Training teams", "Small businesses"],
    pricing: "Freemium",
    monthlyVisits: 11100000,
    trafficLabel: "11.1M monthly visits",
    recommendation: "A useful comparison point if you are shopping for practical business video rather than cinematic generation.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "beautifulai",
    name: "Beautiful.ai",
    vendor: "Beautiful.ai",
    logoLetter: "B",
    accent: "linear-gradient(145deg, #0ea5e9, #14b8a6)",
    url: "https://www.beautiful.ai/",
    summary: "A presentation platform that automates layout polish and speeds up slide creation for operators and GTM teams.",
    categories: ["Productivity", "Design", "Sales"],
    audience: ["Founders", "Sales teams", "Marketers"],
    pricing: "Paid",
    monthlyVisits: 3200000,
    trafficLabel: "3.2M monthly visits",
    recommendation: "A strong pick when your team makes lots of decks and wants more polish with less design labor.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "tome",
    name: "Tome",
    vendor: "Tome",
    logoLetter: "T",
    accent: "linear-gradient(145deg, #111827, #2563eb)",
    url: "https://tome.app/",
    summary: "A narrative-first presentation and storytelling workspace for framing ideas, pitches, and structured visual briefs.",
    categories: ["Productivity", "Design", "Writing"],
    audience: ["Founders", "PMs", "Marketing teams"],
    pricing: "Freemium",
    monthlyVisits: 2400000,
    trafficLabel: "2.4M monthly visits",
    recommendation: "Useful when you want presentation output to feel more like a guided story than a traditional slide deck.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "pitch",
    name: "Pitch",
    vendor: "Pitch",
    logoLetter: "P",
    accent: "linear-gradient(145deg, #111827, #4f46e5)",
    url: "https://pitch.com/",
    summary: "A collaborative presentation platform with AI assists and startup-native workflows for decks, updates, and storytelling.",
    categories: ["Productivity", "Design"],
    audience: ["Startups", "GTM teams", "Operators"],
    pricing: "Freemium",
    monthlyVisits: 3200000,
    trafficLabel: "3.2M monthly visits",
    recommendation: "A credible option if you want collaborative presentation work to feel more product-native than slideware-heavy.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "githubcopilot",
    name: "GitHub Copilot",
    vendor: "GitHub",
    logoLetter: "G",
    accent: "linear-gradient(145deg, #111827, #6366f1)",
    url: "https://github.com/features/copilot",
    summary: "A category-defining coding assistant embedded into developer workflows across IDEs, pull requests, and enterprise codebases.",
    categories: ["Coding", "Productivity"],
    audience: ["Developers", "Engineering teams", "Enterprises"],
    pricing: "Paid",
    monthlyVisits: 65000000,
    trafficLabel: "65.0M monthly visits",
    recommendation: "Still a mandatory comparison point if your team is evaluating serious coding copilots for day-to-day delivery work.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "codeium",
    name: "Codeium",
    vendor: "Codeium",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #111827, #14b8a6)",
    url: "https://codeium.com/",
    summary: "A popular AI coding assistant brand spanning autocomplete, chat, and agent-like developer workflows.",
    categories: ["Coding"],
    audience: ["Developers", "Startups", "Teams comparing copilots"],
    pricing: "Freemium",
    monthlyVisits: 6200000,
    trafficLabel: "6.2M monthly visits",
    recommendation: "A worthwhile benchmark when you want to compare cost, speed, and IDE fit against the biggest coding assistants.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  }
);
