(function () {
  const catalog = window.AI_CATALOG;
  if (!catalog || !Array.isArray(catalog.tools)) {
    return;
  }

  function formatTrafficLabel(monthlyVisits) {
    if (monthlyVisits >= 1000000000) {
      return `${(monthlyVisits / 1000000000).toFixed(1)}B monthly visits`;
    }
    return `${(monthlyVisits / 1000000).toFixed(1)}M monthly visits`;
  }

  const existingIds = new Set(catalog.tools.map((tool) => tool.id));
  const sharedSources = {
    futurepedia: "https://www.futurepedia.io/ai-tools",
    toolify: "https://www.toolify.ai/Best-trending-AI-Tools"
  };

  function addTools(batch) {
    batch.forEach((tool) => {
      if (existingIds.has(tool.id)) {
        return;
      }
      catalog.tools.push({
        ...tool,
        trafficLabel: formatTrafficLabel(tool.monthlyVisits),
        sources: sharedSources
      });
      existingIds.add(tool.id);
    });
  }

  addTools([
    { id: "dust", name: "Dust", vendor: "Dust", logoLetter: "D", accent: "linear-gradient(145deg, #111827, #2563eb)", url: "https://dust.tt/", summary: "A company AI workspace for building internal assistants, agents, and knowledge workflows around your team's tools and data.", categories: ["Assistants", "Automation", "Productivity"], audience: ["Enterprises", "Operations teams", "Knowledge workers"], pricing: "Free / Paid", monthlyVisits: 6400000, recommendation: "A strong addition because internal AI workspaces remain one of the hottest enterprise buying categories.", searchTerms: ["internal ai workspace", "company ai assistant", "knowledge agents"] },
    { id: "hebbia", name: "Hebbia", vendor: "Hebbia", logoLetter: "H", accent: "linear-gradient(145deg, #0f172a, #14b8a6)", url: "https://www.hebbia.com/", summary: "An AI research platform for searching large document sets, extracting evidence, and running repeatable analyst workflows.", categories: ["Research", "Assistants", "Productivity"], audience: ["Analysts", "Finance teams", "Researchers"], pricing: "Paid", monthlyVisits: 3700000, recommendation: "Worth adding because document-heavy AI research products keep pulling strong demand from professional teams.", searchTerms: ["document research ai", "analyst ai workspace", "evidence extraction ai"] },
    { id: "sierra", name: "Sierra", vendor: "Sierra", logoLetter: "S", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://sierra.ai/", summary: "A customer experience platform focused on branded AI agents for service, support, and digital engagement.", categories: ["Assistants", "Sales", "Automation"], audience: ["Support teams", "Brands", "Customer experience teams"], pricing: "Paid", monthlyVisits: 2600000, recommendation: "A timely pick as AI-native customer service agents are becoming a major category.", searchTerms: ["customer service ai agent", "brand support ai", "cx ai platform"] },
    { id: "decagon", name: "Decagon", vendor: "Decagon", logoLetter: "D", accent: "linear-gradient(145deg, #111827, #ec4899)", url: "https://decagon.ai/", summary: "An AI customer support platform for handling tickets, chat, and repetitive service operations at scale.", categories: ["Assistants", "Sales", "Automation"], audience: ["Support teams", "Operations teams", "Enterprises"], pricing: "Paid", monthlyVisits: 3200000, recommendation: "A strong fit because support automation remains a high-intent AI software purchase.", searchTerms: ["customer support ai", "support automation", "ai concierge platform"] },
    { id: "mavenagi", name: "Maven AGI", vendor: "Maven AGI", logoLetter: "M", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://mavenagi.com/", summary: "An enterprise AI agent platform built around support, knowledge, and customer experience workflows.", categories: ["Assistants", "Sales", "Automation"], audience: ["Enterprises", "Support leaders", "Operations teams"], pricing: "Paid", monthlyVisits: 2200000, recommendation: "Useful for buyers comparing enterprise support-agent vendors rather than general chat apps.", searchTerms: ["enterprise ai agent", "support ai platform", "knowledge support automation"] },
    { id: "browseai", name: "Browse AI", vendor: "Browse AI", logoLetter: "B", accent: "linear-gradient(145deg, #14b8a6, #2563eb)", url: "https://www.browse.ai/", summary: "A no-code web scraping and monitoring platform for collecting site data and triggering AI-ready workflows.", categories: ["Automation", "Research", "Productivity"], audience: ["Operators", "Growth teams", "Researchers"], pricing: "Freemium", monthlyVisits: 5100000, recommendation: "A practical addition for users who need structured web data as fuel for AI workflows.", searchTerms: ["no code web scraping", "website monitoring ai", "data extraction automation"] },
    { id: "crewai", name: "CrewAI", vendor: "CrewAI", logoLetter: "C", accent: "linear-gradient(145deg, #f97316, #2563eb)", url: "https://crewai.com/", summary: "A multi-agent platform for building, orchestrating, and operating AI agent teams across complex workflows.", categories: ["Coding", "Automation", "Research"], audience: ["Developers", "AI teams", "Automation builders"], pricing: "Free / Paid", monthlyVisits: 8800000, recommendation: "A major builder platform for teams exploring multi-agent systems beyond single assistants.", searchTerms: ["multi agent platform", "agent orchestration", "ai crew builder"] },
    { id: "openhands", name: "OpenHands", vendor: "OpenHands", logoLetter: "O", accent: "linear-gradient(145deg, #111827, #22c55e)", url: "https://openhands.dev/", summary: "An open platform for cloud coding agents that can plan, edit, review, and execute real software tasks.", categories: ["Coding", "Automation", "Productivity"], audience: ["Developers", "Engineering teams", "Technical founders"], pricing: "Free / Paid", monthlyVisits: 7600000, recommendation: "A hot coding-agent platform with strong open-source and enterprise attention.", searchTerms: ["cloud coding agent", "open source coding agent", "autonomous software agent"] },
    { id: "llamaindex", name: "LlamaIndex", vendor: "LlamaIndex", logoLetter: "L", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.llamaindex.ai/", summary: "A framework and platform for connecting LLMs and agents to documents, data, and production workflows.", categories: ["Coding", "Research", "Automation"], audience: ["Developers", "AI engineers", "Platform teams"], pricing: "Free / Paid", monthlyVisits: 9300000, recommendation: "A core infrastructure name for anyone building retrieval-heavy or agentic AI systems.", searchTerms: ["llm framework", "rag framework", "agent data framework"] },
    { id: "mindstudio", name: "MindStudio", vendor: "MindStudio", logoLetter: "M", accent: "linear-gradient(145deg, #8b5cf6, #ec4899)", url: "https://www.mindstudio.ai/", summary: "A no-code platform for building, deploying, and operating AI agents, automations, and internal tools.", categories: ["Automation", "Assistants", "Productivity"], audience: ["Operators", "Agencies", "Business teams"], pricing: "Freemium", monthlyVisits: 4400000, recommendation: "A strong addition because AI-agent builders with visual workflows are gaining broad traction.", searchTerms: ["no code ai agents", "agent builder", "ai workflow platform"] }
  ]);

  addTools([
    { id: "unstract", name: "Unstract", vendor: "Unstract", logoLetter: "U", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://unstract.com/", summary: "An LLM data extraction platform for pulling structured information from messy documents and business files.", categories: ["Automation", "Coding", "Research"], audience: ["Operations teams", "Developers", "Document-heavy teams"], pricing: "Paid", monthlyVisits: 2100000, recommendation: "A useful pick for teams turning PDFs and business documents into AI-ready structured data.", searchTerms: ["document extraction ai", "llm etl", "structured data from pdf"] },
    { id: "mintlify", name: "Mintlify", vendor: "Mintlify", logoLetter: "M", accent: "linear-gradient(145deg, #111827, #14b8a6)", url: "https://mintlify.com/", summary: "A documentation platform with AI-assisted knowledge search, authoring, and developer-facing content workflows.", categories: ["Coding", "Productivity", "Writing"], audience: ["Developers", "Docs teams", "Startups"], pricing: "Freemium", monthlyVisits: 6700000, recommendation: "A strong documentation pick as AI-native knowledge surfaces keep gaining developer attention.", searchTerms: ["ai documentation", "developer docs platform", "knowledge search docs"] },
    { id: "base44", name: "Base44", vendor: "Base44", logoLetter: "B", accent: "linear-gradient(145deg, #2563eb, #f97316)", url: "https://base44.com/", summary: "An AI app builder focused on quickly turning prompts and ideas into working software products.", categories: ["Coding", "Automation", "Productivity"], audience: ["Founders", "Indie hackers", "Product teams"], pricing: "Freemium", monthlyVisits: 5200000, recommendation: "A hot vibe-building platform with strong appeal for fast product experimentation.", searchTerms: ["ai app builder", "prompt to app", "build software with ai"] },
    { id: "qoder", name: "Qoder", vendor: "Qoder", logoLetter: "Q", accent: "linear-gradient(145deg, #111827, #2563eb)", url: "https://qoder.com/", summary: "An agentic coding platform designed to help developers write, refactor, and navigate software faster.", categories: ["Coding", "Productivity"], audience: ["Developers", "Engineering teams", "Technical founders"], pricing: "Free / Paid", monthlyVisits: 4300000, recommendation: "A strong addition for users comparing the latest editor-native coding assistants.", searchTerms: ["agentic coding platform", "code assistant ai", "developer ai editor"] },
    { id: "tempo", name: "Tempo", vendor: "Tempo", logoLetter: "T", accent: "linear-gradient(145deg, #14b8a6, #2563eb)", url: "https://tempo.new/", summary: "An AI-first product building environment that connects design intent and React implementation workflows.", categories: ["Coding", "Design", "Productivity"], audience: ["Product teams", "Design engineers", "Founders"], pricing: "Freemium", monthlyVisits: 3100000, recommendation: "Useful for teams that want AI to bridge interface design and actual front-end code.", searchTerms: ["react design ai", "ui builder ai", "product design to code"] },
    { id: "knowt", name: "Knowt", vendor: "Knowt", logoLetter: "K", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://knowt.com/", summary: "A study platform with AI notes, flashcards, quizzes, and learning workflows for students.", categories: ["Research", "Productivity", "Writing"], audience: ["Students", "Teachers", "Exam prep users"], pricing: "Free / Paid", monthlyVisits: 18400000, recommendation: "A large-audience study AI product with strong mainstream traction.", searchTerms: ["ai study tools", "flashcards ai", "student learning ai"] },
    { id: "notegpt", name: "NoteGPT", vendor: "NoteGPT", logoLetter: "N", accent: "linear-gradient(145deg, #f97316, #ec4899)", url: "https://notegpt.io/", summary: "An AI learning assistant for summarizing videos, notes, PDFs, and web content into study-ready takeaways.", categories: ["Research", "Productivity", "Writing"], audience: ["Students", "Researchers", "Knowledge workers"], pricing: "Freemium", monthlyVisits: 14200000, recommendation: "A popular all-in-one summarization and learning tool with broad appeal.", searchTerms: ["video summary ai", "pdf summary ai", "learning assistant ai"] },
    { id: "tripoai", name: "Tripo Studio", vendor: "Tripo", logoLetter: "T", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://www.tripo.studio/", summary: "An AI 3D creation workspace for generating models, assets, and scenes from images or text prompts.", categories: ["Design", "Video", "Productivity"], audience: ["3D artists", "Game creators", "Designers"], pricing: "Freemium", monthlyVisits: 9700000, recommendation: "A high-interest 3D generation product with strong creator and game-builder appeal.", searchTerms: ["ai 3d generator", "image to 3d", "3d assets ai"] },
    { id: "vidu", name: "Vidu", vendor: "Vidu", logoLetter: "V", accent: "linear-gradient(145deg, #111827, #ec4899)", url: "https://www.vidu.com/", summary: "An AI video generator built for fast scene creation, stylized motion, and creative prompt-based production.", categories: ["Video", "Design"], audience: ["Creators", "Marketers", "Studios"], pricing: "Freemium", monthlyVisits: 12600000, recommendation: "A notable video platform as AI-native motion tools continue to surge.", searchTerms: ["ai video generator", "text to video ai", "creative motion ai"] },
    { id: "napkin", name: "Napkin AI", vendor: "Napkin", logoLetter: "N", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://www.napkin.ai/", summary: "A visual storytelling tool that turns ideas and rough text into clean diagrams, flows, and business visuals.", categories: ["Design", "Productivity"], audience: ["Consultants", "Product teams", "Operators"], pricing: "Freemium", monthlyVisits: 6100000, recommendation: "A strong fit for users who want quick business visuals rather than slide decks or art generation.", searchTerms: ["business visuals ai", "diagram generator", "visual storytelling ai"] }
  ]);

  addTools([
    { id: "vizard", name: "Vizard", vendor: "Vizard", logoLetter: "V", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://vizard.ai/", summary: "An AI video editing and clipping platform for turning long recordings into short-form social-ready highlights.", categories: ["Video", "Productivity", "Sales"], audience: ["Creators", "Podcasters", "Marketing teams"], pricing: "Freemium", monthlyVisits: 8200000, recommendation: "A strong social-video workflow pick with broad creator demand.", searchTerms: ["video clipping ai", "podcast clips ai", "short form video editor"] },
    { id: "merlin", name: "Merlin AI", vendor: "Merlin", logoLetter: "M", accent: "linear-gradient(145deg, #111827, #f97316)", url: "https://www.getmerlin.in/", summary: "A browser AI assistant for summarizing pages, drafting content, and using multiple top models in one workspace.", categories: ["Assistants", "Productivity", "Writing"], audience: ["Students", "Knowledge workers", "General users"], pricing: "Freemium", monthlyVisits: 11200000, recommendation: "A large-audience browser-side AI tool with continued mainstream interest.", searchTerms: ["browser ai assistant", "multi model browser ai", "page summary assistant"] },
    { id: "harpa", name: "HARPA AI", vendor: "HARPA AI", logoLetter: "H", accent: "linear-gradient(145deg, #2563eb, #ec4899)", url: "https://harpa.ai/", summary: "A browser agent for summarizing, searching, monitoring pages, and automating routine web tasks.", categories: ["Automation", "Research", "Assistants"], audience: ["Researchers", "Analysts", "Power users"], pricing: "Free / Paid", monthlyVisits: 5400000, recommendation: "A practical browser-automation AI with strong day-to-day utility.", searchTerms: ["browser agent ai", "page monitor ai", "web automation assistant"] },
    { id: "cartesia", name: "Cartesia", vendor: "Cartesia", logoLetter: "C", accent: "linear-gradient(145deg, #14b8a6, #111827)", url: "https://cartesia.ai/", summary: "A real-time voice AI platform for low-latency text-to-speech and expressive audio applications.", categories: ["Audio", "Coding", "Assistants"], audience: ["Developers", "Voice teams", "Agent builders"], pricing: "Usage-based", monthlyVisits: 3900000, recommendation: "A timely addition as voice agents and expressive speech stacks keep growing.", searchTerms: ["real time tts", "voice ai api", "expressive speech platform"] },
    { id: "wellsaid", name: "WellSaid Labs", vendor: "WellSaid", logoLetter: "W", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://wellsaid.io/", summary: "A studio-grade AI voice platform for narration, training content, and professional synthetic speech.", categories: ["Audio", "Productivity"], audience: ["L&D teams", "Studios", "Marketing teams"], pricing: "Paid", monthlyVisits: 2700000, recommendation: "A strong professional voice brand for users who value polish over novelty.", searchTerms: ["ai voice studio", "professional tts", "training narration ai"] },
    { id: "resemble", name: "Resemble AI", vendor: "Resemble", logoLetter: "R", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://www.resemble.ai/", summary: "A voice AI platform for speech generation, cloning, dubbing, and developer-ready audio experiences.", categories: ["Audio", "Video", "Coding"], audience: ["Developers", "Studios", "Media teams"], pricing: "Usage-based", monthlyVisits: 3600000, recommendation: "A good fit for teams building audio experiences or localized media workflows.", searchTerms: ["voice cloning ai", "speech generation api", "audio dubbing ai"] },
    { id: "runcomfy", name: "RunComfy", vendor: "RunComfy", logoLetter: "R", accent: "linear-gradient(145deg, #111827, #8b5cf6)", url: "https://www.runcomfy.com/", summary: "A cloud platform for running ComfyUI workflows, image pipelines, and model experiments without local setup.", categories: ["Design", "Coding", "Video"], audience: ["Creators", "AI builders", "Studios"], pricing: "Usage-based", monthlyVisits: 4700000, recommendation: "A useful addition for power users working with advanced image and video generation workflows.", searchTerms: ["comfyui cloud", "image workflow ai", "model pipeline hosting"] },
    { id: "segmind", name: "Segmind", vendor: "Segmind", logoLetter: "S", accent: "linear-gradient(145deg, #2563eb, #f97316)", url: "https://www.segmind.com/", summary: "A media generation platform for developers shipping image, video, and creative AI workflows through APIs and pipelines.", categories: ["Design", "Coding", "Video"], audience: ["Developers", "Creative engineers", "Startups"], pricing: "Usage-based", monthlyVisits: 4200000, recommendation: "A builder-friendly media AI platform with broad coverage across generation tasks.", searchTerms: ["media ai api", "image generation api", "video generation workflow"] },
    { id: "higgsfield", name: "Higgsfield", vendor: "Higgsfield", logoLetter: "H", accent: "linear-gradient(145deg, #111827, #ef4444)", url: "https://higgsfield.ai/", summary: "An AI video and image generation platform focused on high-style motion, cinematic outputs, and creator workflows.", categories: ["Video", "Design"], audience: ["Creators", "Studios", "Marketing teams"], pricing: "Freemium", monthlyVisits: 7100000, recommendation: "A high-buzz creative video platform with clear visual momentum.", searchTerms: ["cinematic ai video", "image to video ai", "creative generation platform"] },
    { id: "joggai", name: "JoggAI", vendor: "JoggAI", logoLetter: "J", accent: "linear-gradient(145deg, #f97316, #fb7185)", url: "https://www.jogg.ai/", summary: "An AI video maker for avatar-led product videos, ad creatives, and lightweight marketing content.", categories: ["Video", "Sales"], audience: ["Marketers", "E-commerce teams", "Agencies"], pricing: "Freemium", monthlyVisits: 3800000, recommendation: "A practical ad-video product with strong commercial intent.", searchTerms: ["avatar ad video ai", "marketing video ai", "product video generator"] }
  ]);

  addTools([
    { id: "zebracat", name: "Zebracat", vendor: "Zebracat", logoLetter: "Z", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.zebracat.ai/", summary: "An AI video generation platform for scripts, visuals, and social-ready marketing clips.", categories: ["Video", "Sales", "Writing"], audience: ["Creators", "Growth teams", "Agencies"], pricing: "Freemium", monthlyVisits: 5900000, recommendation: "A strong fit for teams producing promotional clips quickly from text inputs.", searchTerms: ["script to video ai", "marketing clips ai", "social video generator"] },
    { id: "rask", name: "Rask AI", vendor: "Rask", logoLetter: "R", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://www.rask.ai/", summary: "A localization and dubbing platform for translating videos, preserving voice tone, and scaling global content.", categories: ["Translation", "Video", "Audio"], audience: ["Media teams", "Educators", "Global marketers"], pricing: "Paid", monthlyVisits: 4900000, recommendation: "A useful global-content tool as video translation keeps moving mainstream.", searchTerms: ["video dubbing ai", "video translation ai", "localization platform ai"] },
    { id: "observeai", name: "Observe.AI", vendor: "Observe.AI", logoLetter: "O", accent: "linear-gradient(145deg, #111827, #14b8a6)", url: "https://www.observe.ai/", summary: "A contact-center intelligence platform for QA, coaching, analytics, and voice AI agents.", categories: ["Audio", "Sales", "Automation"], audience: ["Call centers", "Support teams", "Revenue teams"], pricing: "Paid", monthlyVisits: 3000000, recommendation: "A strong operational AI product with durable demand in support and CX.", searchTerms: ["call center ai", "contact center intelligence", "voice qa ai"] },
    { id: "forethought", name: "Forethought", vendor: "Forethought", logoLetter: "F", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://forethought.ai/", summary: "A customer service AI platform for support agents, automated deflection, and helpdesk workflows.", categories: ["Assistants", "Sales", "Automation"], audience: ["Support teams", "CX leaders", "Enterprises"], pricing: "Paid", monthlyVisits: 2500000, recommendation: "A notable support-AI vendor for buyers comparing serious service automation platforms.", searchTerms: ["customer support ai", "helpdesk automation ai", "service agent ai"] },
    { id: "pylon", name: "Pylon", vendor: "Pylon", logoLetter: "P", accent: "linear-gradient(145deg, #111827, #2563eb)", url: "https://usepylon.com/", summary: "A support platform blending ticketing, customer communication, and AI assistance for fast-moving teams.", categories: ["Sales", "Productivity", "Assistants"], audience: ["Support teams", "Startups", "Operations teams"], pricing: "Paid", monthlyVisits: 2200000, recommendation: "A good addition because support tooling is increasingly being rebuilt around AI-native workflows.", searchTerms: ["support platform ai", "ticketing ai", "customer support workspace"] },
    { id: "freed", name: "Freed", vendor: "Freed", logoLetter: "F", accent: "linear-gradient(145deg, #14b8a6, #2563eb)", url: "https://www.getfreed.ai/", summary: "An AI medical scribe for generating clinical notes, summaries, and documentation from patient visits.", categories: ["Productivity", "Meetings", "Writing"], audience: ["Clinicians", "Private practices", "Medical teams"], pricing: "Paid", monthlyVisits: 4200000, recommendation: "A high-intent vertical AI product with clear productivity value in healthcare.", searchTerms: ["medical scribe ai", "clinical notes ai", "doctor documentation ai"] },
    { id: "jenni", name: "Jenni AI", vendor: "Jenni", logoLetter: "J", accent: "linear-gradient(145deg, #2563eb, #ec4899)", url: "https://jenni.ai/", summary: "An AI writing assistant oriented around essays, papers, citations, and academic drafting workflows.", categories: ["Writing", "Research", "Productivity"], audience: ["Students", "Researchers", "Writers"], pricing: "Freemium", monthlyVisits: 7800000, recommendation: "A major academic-writing AI brand with sustained demand.", searchTerms: ["academic writing ai", "essay ai", "citation writing assistant"] },
    { id: "lex", name: "Lex", vendor: "Lex", logoLetter: "L", accent: "linear-gradient(145deg, #111827, #f97316)", url: "https://lex.page/", summary: "A minimalist AI writing environment focused on clean drafting, revision, and collaboration.", categories: ["Writing", "Productivity"], audience: ["Writers", "Founders", "Knowledge workers"], pricing: "Freemium", monthlyVisits: 2300000, recommendation: "A good fit for users who want focused AI writing rather than bulky suite software.", searchTerms: ["minimal writing ai", "drafting tool ai", "writing workspace ai"] },
    { id: "tana", name: "Tana", vendor: "Tana", logoLetter: "T", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://tana.inc/", summary: "A knowledge workspace for notes, meetings, and structured personal systems with AI assistance woven in.", categories: ["Productivity", "Research"], audience: ["Knowledge workers", "Researchers", "Founders"], pricing: "Paid", monthlyVisits: 3100000, recommendation: "A notable knowledge-system tool for users building more structured AI-enhanced workflows.", searchTerms: ["knowledge workspace ai", "notes ai", "structured note taking ai"] },
    { id: "capacities", name: "Capacities", vendor: "Capacities", logoLetter: "C", accent: "linear-gradient(145deg, #8b5cf6, #2563eb)", url: "https://capacities.io/", summary: "A note-taking and knowledge management workspace with object-based organization and AI help for thinking work.", categories: ["Productivity", "Research"], audience: ["Knowledge workers", "Students", "Writers"], pricing: "Freemium", monthlyVisits: 4600000, recommendation: "A strong modern notes product with visible momentum among power users.", searchTerms: ["knowledge management ai", "note taking workspace", "personal knowledge ai"] }
  ]);

  addTools([
    { id: "reflect", name: "Reflect", vendor: "Reflect", logoLetter: "R", accent: "linear-gradient(145deg, #111827, #22c55e)", url: "https://reflect.app/", summary: "A note-taking app with backlinks, search, and AI support for writing, recall, and connected thinking.", categories: ["Productivity", "Writing"], audience: ["Writers", "Knowledge workers", "Founders"], pricing: "Paid", monthlyVisits: 2600000, recommendation: "A useful notes-and-writing product for users who want a quieter AI workspace.", searchTerms: ["notes with ai", "backlinks notes ai", "personal writing workspace"] },
    { id: "castmagic", name: "Castmagic", vendor: "Castmagic", logoLetter: "C", accent: "linear-gradient(145deg, #2563eb, #f97316)", url: "https://www.castmagic.io/", summary: "A repurposing platform that turns audio and video recordings into summaries, drafts, and content assets.", categories: ["Writing", "Audio", "Productivity"], audience: ["Podcasters", "Creators", "Marketing teams"], pricing: "Paid", monthlyVisits: 2900000, recommendation: "A practical content-ops product for turning recordings into reusable output quickly.", searchTerms: ["podcast repurposing ai", "audio to content ai", "content repurpose tool"] },
    { id: "presentationsai", name: "Presentations.AI", vendor: "Presentations.AI", logoLetter: "P", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.presentations.ai/", summary: "An AI presentation maker for turning ideas, notes, and prompts into polished slide decks quickly.", categories: ["Productivity", "Design", "Writing"], audience: ["Consultants", "Sales teams", "Founders"], pricing: "Freemium", monthlyVisits: 6800000, recommendation: "A clear fit for users who want slide generation with more business polish than generic design tools.", searchTerms: ["ai presentation maker", "slide deck ai", "pitch deck generator"] },
    { id: "eraser", name: "Eraser", vendor: "Eraser", logoLetter: "E", accent: "linear-gradient(145deg, #111827, #ec4899)", url: "https://www.eraser.io/", summary: "A diagramming and technical design tool with AI support for system maps, docs, and architecture visuals.", categories: ["Coding", "Design", "Productivity"], audience: ["Engineers", "Architects", "Product teams"], pricing: "Freemium", monthlyVisits: 5200000, recommendation: "A strong product for technical teams producing architecture and design artifacts.", searchTerms: ["architecture diagram ai", "technical docs ai", "diagramming assistant"] },
    { id: "hex", name: "Hex", vendor: "Hex", logoLetter: "H", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://hex.tech/", summary: "A collaborative analytics workspace with AI help for notebooks, dashboards, and business analysis.", categories: ["Research", "Coding", "Productivity"], audience: ["Analysts", "Data teams", "Business teams"], pricing: "Paid", monthlyVisits: 5400000, recommendation: "A useful analytics platform as AI-assisted data work becomes more mainstream.", searchTerms: ["analytics workspace ai", "notebook ai analytics", "business data ai"] },
    { id: "akkio", name: "Akkio", vendor: "Akkio", logoLetter: "A", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://www.akkio.com/", summary: "An AI analytics platform for forecasting, reporting, and no-code data workflows inside business teams.", categories: ["Research", "Sales", "Automation"], audience: ["Marketing teams", "Revenue teams", "Analysts"], pricing: "Paid", monthlyVisits: 2100000, recommendation: "A practical no-code analytics pick for business users who want AI without a heavy data stack.", searchTerms: ["no code analytics ai", "forecasting ai", "business reporting ai"] },
    { id: "marketmuse", name: "MarketMuse", vendor: "MarketMuse", logoLetter: "M", accent: "linear-gradient(145deg, #14b8a6, #2563eb)", url: "https://www.marketmuse.com/", summary: "An AI content planning and optimization platform for editorial strategy, coverage gaps, and SEO workflows.", categories: ["Writing", "Research", "Sales"], audience: ["SEO teams", "Content strategists", "Agencies"], pricing: "Paid", monthlyVisits: 2600000, recommendation: "A solid strategic SEO platform for teams focused on content planning, not just writing speed.", searchTerms: ["content planning ai", "seo research ai", "topic strategy platform"] },
    { id: "frase", name: "Frase", vendor: "Frase", logoLetter: "F", accent: "linear-gradient(145deg, #111827, #14b8a6)", url: "https://www.frase.io/", summary: "An SEO writing and optimization tool for outlines, briefs, and search-focused content production.", categories: ["Writing", "Research", "Sales"], audience: ["Content marketers", "SEO teams", "Agencies"], pricing: "Paid", monthlyVisits: 4900000, recommendation: "A durable SEO-writing product with strong relevance to AI content buyers.", searchTerms: ["seo writing ai", "content brief ai", "search content optimization"] },
    { id: "smartcat", name: "Smartcat", vendor: "Smartcat", logoLetter: "S", accent: "linear-gradient(145deg, #2563eb, #f97316)", url: "https://www.smartcat.com/", summary: "A global content platform combining translation, localization, and AI support for multilingual teams.", categories: ["Translation", "Productivity", "Sales"], audience: ["Global teams", "Localization leads", "Agencies"], pricing: "Paid", monthlyVisits: 6500000, recommendation: "A strong localization platform with clear AI value for scaling content globally.", searchTerms: ["translation platform ai", "localization ai", "global content platform"] },
    { id: "overchat", name: "Overchat AI", vendor: "Overchat", logoLetter: "O", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://overchat.ai/", summary: "An all-in-one AI chat app that brings multiple leading models into a single consumer-friendly workspace.", categories: ["Assistants", "Productivity", "Writing"], audience: ["General users", "Students", "Knowledge workers"], pricing: "Freemium", monthlyVisits: 7600000, recommendation: "A strong mainstream pick for users who want a multi-model AI hub instead of one provider.", searchTerms: ["multi model ai chat", "all in one ai app", "consumer ai workspace"] }
  ]);
}());
