(function () {
  const catalog = window.AI_CATALOG;
  if (!catalog || !Array.isArray(catalog.tools)) {
    return;
  }

  function formatTrafficLabel(monthlyVisits) {
    if (monthlyVisits >= 1000000000) {
      return `${(monthlyVisits / 1000000000).toFixed(1)}B monthly visits`;
    }
    return `${(monthlyVisits / 1000000).toFixed(1)}M monthly visits`;
  }

  const extraTools = [
    { id: "promeai", name: "PromeAI", vendor: "PromeAI", logoLetter: "P", accent: "linear-gradient(145deg, #2563eb, #ec4899)", url: "https://www.promeai.com/", summary: "A visual generation and rendering tool often used for architecture, interiors, and concept presentation.", categories: ["Design"], audience: ["Architects", "Designers", "Visualization teams"], pricing: "Freemium", monthlyVisits: 7800000, recommendation: "A helpful addition because category-specific visual tools often convert better than general image products.", searchTerms: ["architectural render ai", "interior design ai"] },
    { id: "looka", name: "Looka", vendor: "Looka", logoLetter: "L", accent: "linear-gradient(145deg, #111827, #22c55e)", url: "https://looka.com/", summary: "An AI logo and brand kit builder aimed at founders and small businesses launching quickly.", categories: ["Design", "Sales"], audience: ["Founders", "Small businesses", "Agencies"], pricing: "Paid", monthlyVisits: 15700000, recommendation: "A practical inclusion because logo and brand-kit buyers often search directly for dedicated tools.", searchTerms: ["logo maker ai", "brand kit ai"] },
    { id: "logoai", name: "LogoAI", vendor: "LogoAI", logoLetter: "L", accent: "linear-gradient(145deg, #2563eb, #0ea5e9)", url: "https://www.logoai.com/", summary: "A logo generation platform for small businesses that want quick brand assets and simple identity packages.", categories: ["Design", "Sales"], audience: ["Small businesses", "Founders", "Freelancers"], pricing: "Paid", monthlyVisits: 7100000, recommendation: "Useful in a commercial directory because many buyers want speed and utility over agency-grade craft.", searchTerms: ["logo ai", "brand maker ai"] },
    { id: "brandmark", name: "Brandmark", vendor: "Brandmark", logoLetter: "B", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://brandmark.io/", summary: "A logo and branding generator for startups, solo builders, and fast-launch commercial identities.", categories: ["Design", "Sales"], audience: ["Founders", "Agencies", "Small businesses"], pricing: "Paid", monthlyVisits: 5300000, recommendation: "A useful brand-design listing for buyers who want identity assets immediately and online.", searchTerms: ["brandmark io", "brand design ai"] },
    { id: "stockimg", name: "Stockimg AI", vendor: "Stockimg AI", logoLetter: "S", accent: "linear-gradient(145deg, #0ea5e9, #ec4899)", url: "https://stockimg.ai/", summary: "A generation tool for logos, posters, social images, and commercial creative assets.", categories: ["Design", "Sales"], audience: ["Marketers", "Creators", "Small businesses"], pricing: "Freemium", monthlyVisits: 4200000, recommendation: "A good fit when the buyer cares about business-ready asset types more than pure art generation.", searchTerms: ["poster ai", "social creative ai", "logo generation"] },
    { id: "designsai", name: "Designs.ai", vendor: "Designs.ai", logoLetter: "D", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://designs.ai/", summary: "A design suite spanning logos, videos, voiceovers, and marketing creative with AI assistance.", categories: ["Design", "Video", "Audio"], audience: ["Marketers", "Agencies", "Small businesses"], pricing: "Freemium", monthlyVisits: 5700000, recommendation: "Useful when a team wants a broad creative toolkit instead of buying many narrow single-purpose tools.", searchTerms: ["creative suite ai", "logo video voice ai"] },
    { id: "cleanuppictures", name: "Cleanup.pictures", vendor: "Cleanup.pictures", logoLetter: "C", accent: "linear-gradient(145deg, #111827, #0ea5e9)", url: "https://cleanup.pictures/", summary: "An image cleanup tool for object removal and simple visual editing without a full design workflow.", categories: ["Design"], audience: ["Designers", "Marketers", "E-commerce teams"], pricing: "Freemium", monthlyVisits: 6300000, recommendation: "A practical addition because single-purpose image cleanup utilities remain high-intent buying tools.", searchTerms: ["object removal ai", "cleanup photos"] },
    { id: "picwish", name: "PicWish", vendor: "PicWish", logoLetter: "P", accent: "linear-gradient(145deg, #0ea5e9, #14b8a6)", url: "https://picwish.com/", summary: "An image utility suite covering background removal, enhancement, and commerce-friendly photo edits.", categories: ["Design", "Video"], audience: ["E-commerce teams", "Creators", "Marketers"], pricing: "Freemium", monthlyVisits: 9700000, recommendation: "Useful where practical product photo workflows matter more than artistic generation.", searchTerms: ["background remover", "photo enhancement ai"] },
    { id: "photoai", name: "PhotoAI", vendor: "PhotoAI", logoLetter: "P", accent: "linear-gradient(145deg, #8b5cf6, #2563eb)", url: "https://photoai.com/", summary: "An AI photography product for generated portraits, profile images, and personal brand visuals.", categories: ["Design"], audience: ["Creators", "Professionals", "Marketers"], pricing: "Paid", monthlyVisits: 5900000, recommendation: "A good inclusion for buyers looking specifically for headshots and synthetic personal photography.", searchTerms: ["ai headshots", "profile photo ai", "portrait ai"] },
    { id: "pixverse", name: "PixVerse", vendor: "PixVerse", logoLetter: "P", accent: "linear-gradient(145deg, #2563eb, #f43f5e)", url: "https://pixverse.ai/", summary: "A consumer-friendly video generation product for text-to-video and image animation use cases.", categories: ["Video", "Design"], audience: ["Creators", "Social teams", "Designers"], pricing: "Freemium", monthlyVisits: 11800000, recommendation: "A relevant listing because the image-to-video buying category is expanding quickly.", searchTerms: ["pixverse ai", "image to video", "video generator"] },
    { id: "viggle", name: "Viggle", vendor: "Viggle", logoLetter: "V", accent: "linear-gradient(145deg, #111827, #8b5cf6)", url: "https://viggle.ai/", summary: "A motion-focused creation tool for character animation, meme-ready video, and social-first remixes.", categories: ["Video", "Design"], audience: ["Creators", "Social teams", "Meme communities"], pricing: "Free / Paid", monthlyVisits: 8400000, recommendation: "A useful addition where playful motion content and internet-native creation matter.", searchTerms: ["character animation ai", "motion remix ai"] },
    { id: "deepgram", name: "Deepgram", vendor: "Deepgram", logoLetter: "D", accent: "linear-gradient(145deg, #0f172a, #22c55e)", url: "https://deepgram.com/", summary: "A voice AI infrastructure platform for speech recognition, TTS, and real-time audio applications.", categories: ["Audio", "Coding", "Automation"], audience: ["Developers", "Product teams", "Voice startups"], pricing: "Paid", monthlyVisits: 2900000, recommendation: "An important inclusion for technical buyers evaluating voice APIs and production speech infrastructure.", searchTerms: ["speech api", "stt api", "tts api"] },
    { id: "assemblyai", name: "AssemblyAI", vendor: "AssemblyAI", logoLetter: "A", accent: "linear-gradient(145deg, #2563eb, #111827)", url: "https://www.assemblyai.com/", summary: "A speech AI API provider for transcription, audio intelligence, and developer-first voice products.", categories: ["Audio", "Coding", "Automation"], audience: ["Developers", "Startups", "Voice teams"], pricing: "Paid", monthlyVisits: 2500000, recommendation: "Useful for buyers comparing voice infrastructure rather than creator-facing apps.", searchTerms: ["speech to text api", "audio intelligence", "voice developer api"] },
    { id: "revai", name: "Rev AI", vendor: "Rev", logoLetter: "R", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://www.rev.ai/", summary: "A speech technology API offering transcription and voice processing on top of Rev's audio brand.", categories: ["Audio", "Coding", "Productivity"], audience: ["Developers", "Media teams", "Enterprise teams"], pricing: "Paid", monthlyVisits: 2200000, recommendation: "A credible inclusion because enterprise voice buyers often prefer established transcription brands.", searchTerms: ["rev ai", "transcription api"] },
    { id: "cohere", name: "Cohere", vendor: "Cohere", logoLetter: "C", accent: "linear-gradient(145deg, #111827, #2563eb)", url: "https://cohere.com/", summary: "A model and enterprise AI platform for text generation, retrieval, and business AI deployment.", categories: ["Coding", "Assistants", "Research"], audience: ["Developers", "Enterprises", "AI teams"], pricing: "Paid", monthlyVisits: 4200000, recommendation: "Important for buyers comparing model providers and enterprise-facing AI stacks.", searchTerms: ["llm provider", "enterprise ai platform", "text generation api"] },
    { id: "togetherai", name: "Together AI", vendor: "Together AI", logoLetter: "T", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://www.together.ai/", summary: "A model platform for inference, fine-tuning, and open-model developer workflows.", categories: ["Coding", "Research", "Automation"], audience: ["Developers", "AI teams", "Startups"], pricing: "Paid", monthlyVisits: 3900000, recommendation: "A strong addition for builder audiences comparing infrastructure around open models.", searchTerms: ["open model api", "inference platform", "fine tuning ai"] },
    { id: "groqcloud", name: "GroqCloud", vendor: "Groq", logoLetter: "G", accent: "linear-gradient(145deg, #111827, #f97316)", url: "https://groq.com/", summary: "A fast inference platform known for high-speed model serving and developer benchmarking interest.", categories: ["Coding", "Research"], audience: ["Developers", "AI engineers", "Startups"], pricing: "Paid", monthlyVisits: 6100000, recommendation: "Worth including because performance-minded developers often search specifically for Groq.", searchTerms: ["groq api", "fast inference", "llm speed"] },
    { id: "anyscale", name: "Anyscale", vendor: "Anyscale", logoLetter: "A", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://www.anyscale.com/", summary: "A Ray-oriented AI infrastructure company for model serving, scaling, and enterprise AI systems.", categories: ["Coding", "Automation"], audience: ["AI engineers", "Enterprises", "Platform teams"], pricing: "Paid", monthlyVisits: 1700000, recommendation: "A useful infrastructure listing for technical buyers further down the deployment stack.", searchTerms: ["ray serve", "model serving", "ai infrastructure"] },
    { id: "writer", name: "Writer", vendor: "Writer", logoLetter: "W", accent: "linear-gradient(145deg, #111827, #06b6d4)", url: "https://writer.com/", summary: "An enterprise AI platform with strong positioning around writing, brand governance, and internal AI deployment.", categories: ["Writing", "Productivity", "Assistants"], audience: ["Enterprises", "Marketing teams", "Operations teams"], pricing: "Paid", monthlyVisits: 4500000, recommendation: "High-signal for enterprise buyers who care about governance and company-safe writing workflows.", searchTerms: ["enterprise writing ai", "brand governance ai"] },
    { id: "harvey", name: "Harvey", vendor: "Harvey", logoLetter: "H", accent: "linear-gradient(145deg, #0f172a, #2563eb)", url: "https://www.harvey.ai/", summary: "A legal AI platform built for law firms and professional services teams handling complex document work.", categories: ["Research", "Writing", "Productivity"], audience: ["Law firms", "Legal teams", "Professional services"], pricing: "Paid", monthlyVisits: 2400000, recommendation: "A credible vertical AI inclusion for high-intent professional buyers.", searchTerms: ["legal ai", "law firm ai", "document review ai"] },
    { id: "spellbook", name: "Spellbook", vendor: "Spellbook", logoLetter: "S", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://www.spellbook.legal/", summary: "A contract drafting and legal review assistant designed for lawyers working directly in documents.", categories: ["Writing", "Productivity", "Research"], audience: ["Lawyers", "Legal ops", "In-house counsel"], pricing: "Paid", monthlyVisits: 1800000, recommendation: "A useful inclusion because contract-focused AI buyers often search for specific legal drafting tools.", searchTerms: ["contract ai", "legal drafting ai", "lawyer copilot"] },
    { id: "cocounsel", name: "CoCounsel", vendor: "Thomson Reuters", logoLetter: "C", accent: "linear-gradient(145deg, #f97316, #b91c1c)", url: "https://legal.thomsonreuters.com/en/products/cocounsel", summary: "A professional legal assistant for document review, research, and workflow support inside legal teams.", categories: ["Research", "Writing", "Productivity"], audience: ["Legal teams", "Law firms", "Enterprise counsel"], pricing: "Paid", monthlyVisits: 1600000, recommendation: "Important for professional buyers comparing trusted legal vendors rather than startup-only tools.", searchTerms: ["co counsel", "legal assistant ai", "thomson reuters ai"] },
    { id: "clickupbrain", name: "ClickUp Brain", vendor: "ClickUp", logoLetter: "C", accent: "linear-gradient(145deg, #7c3aed, #ec4899)", url: "https://clickup.com/ai", summary: "ClickUp's AI layer for project work, docs, task support, and team productivity flows.", categories: ["Productivity", "Writing", "Assistants"], audience: ["Project teams", "Startups", "Operations teams"], pricing: "Paid", monthlyVisits: 8700000, recommendation: "Useful when buyers want AI embedded inside project management rather than in a separate app.", searchTerms: ["clickup ai", "project management ai"] },
    { id: "asanaai", name: "Asana AI", vendor: "Asana", logoLetter: "A", accent: "linear-gradient(145deg, #ec4899, #f97316)", url: "https://asana.com/ai", summary: "AI features inside Asana for project planning, summaries, and operational work coordination.", categories: ["Productivity", "Automation"], audience: ["Project teams", "Operations teams", "Enterprises"], pricing: "Paid", monthlyVisits: 13200000, recommendation: "A sensible addition because many buyers prefer AI in the work-management product they already run.", searchTerms: ["asana ai", "work management ai"] },
    { id: "mondayai", name: "monday AI", vendor: "monday.com", logoLetter: "M", accent: "linear-gradient(145deg, #2563eb, #f97316)", url: "https://monday.com/ai", summary: "monday.com's AI layer for workflow building, summaries, task support, and operational collaboration.", categories: ["Productivity", "Automation"], audience: ["Operations teams", "Project teams", "Enterprises"], pricing: "Paid", monthlyVisits: 14500000, recommendation: "A practical listing for operations-heavy teams evaluating AI through existing workflow software.", searchTerms: ["monday com ai", "workflow ai", "project ai"] }
  ].map((tool) => ({
    ...tool,
    trafficLabel: formatTrafficLabel(tool.monthlyVisits),
    sources: {
      futurepedia: "https://www.futurepedia.io/ai-tools",
      toolify: "https://www.toolify.ai/Best-trending-AI-Tools"
    }
  }));

  const existingIds = new Set(catalog.tools.map((tool) => tool.id));
  extraTools.forEach((tool) => {
    if (!existingIds.has(tool.id)) {
      catalog.tools.push(tool);
      existingIds.add(tool.id);
    }
  });
}());
