(function () {
  const catalog = window.AI_CATALOG;
  if (!catalog || !Array.isArray(catalog.tools)) {
    return;
  }

  function formatTrafficLabel(monthlyVisits) {
    if (monthlyVisits >= 1000000000) {
      return `${(monthlyVisits / 1000000000).toFixed(1)}B monthly visits`;
    }
    return `${(monthlyVisits / 1000000).toFixed(1)}M monthly visits`;
  }

  const extraTools = [
    { id: "microsoftcopilot", name: "Microsoft Copilot", vendor: "Microsoft", logoLetter: "C", accent: "linear-gradient(145deg, #2563eb, #7c3aed)", url: "https://copilot.microsoft.com/", summary: "Microsoft's mainstream AI assistant woven into Windows, Bing, Edge, and Microsoft 365 workflows.", categories: ["Assistants", "Productivity", "Research"], audience: ["Microsoft 365 teams", "Professionals", "Students"], pricing: "Free / Paid", monthlyVisits: 188000000, recommendation: "A strong option when your stack already runs on Microsoft products and enterprise controls matter.", searchTerms: ["bing copilot", "m365 ai", "office ai"] },
    { id: "mistralchat", name: "Mistral Le Chat", vendor: "Mistral", logoLetter: "M", accent: "linear-gradient(145deg, #111827, #f97316)", url: "https://chat.mistral.ai/", summary: "A fast general assistant from Mistral for chat, reasoning, and document-oriented work.", categories: ["Assistants", "Research", "Coding"], audience: ["Developers", "Analysts", "Power users"], pricing: "Free / Paid", monthlyVisits: 46000000, recommendation: "Worth comparing when you want another frontier-model option beyond the usual assistant leaders.", searchTerms: ["le chat", "mistral ai", "mistral assistant"] },
    { id: "huggingchat", name: "HuggingChat", vendor: "Hugging Face", logoLetter: "H", accent: "linear-gradient(145deg, #f59e0b, #f97316)", url: "https://huggingface.co/chat/", summary: "An open-model chat surface for users who want broad community model access in one place.", categories: ["Assistants", "Research", "Coding"], audience: ["Developers", "Researchers", "Open-source users"], pricing: "Free", monthlyVisits: 21000000, recommendation: "Useful when openness and model variety matter more than a tightly polished consumer interface.", searchTerms: ["hugging face chat", "open model chat"] },
    { id: "pi", name: "Pi", vendor: "Inflection", logoLetter: "P", accent: "linear-gradient(145deg, #06b6d4, #3b82f6)", url: "https://pi.ai/", summary: "A conversation-first personal AI assistant designed around calm, supportive chat rather than heavy workflows.", categories: ["Assistants", "Productivity"], audience: ["Consumers", "Students", "Light users"], pricing: "Free", monthlyVisits: 18000000, recommendation: "A sensible addition for users who prefer a more companion-like assistant experience.", searchTerms: ["pi ai", "inflection ai", "personal ai"] },
    { id: "andi", name: "Andi Search", vendor: "Andi", logoLetter: "A", accent: "linear-gradient(145deg, #0f172a, #14b8a6)", url: "https://andisearch.com/", summary: "An AI-native search experience focused on concise answers and lightweight web discovery.", categories: ["Research", "Assistants"], audience: ["Researchers", "Students", "Knowledge workers"], pricing: "Free", monthlyVisits: 6900000, recommendation: "Good for buyers who want search-first AI rather than a full chat workspace.", searchTerms: ["ai search", "answer engine"] },
    { id: "komo", name: "Komo", vendor: "Komo", logoLetter: "K", accent: "linear-gradient(145deg, #111827, #22c55e)", url: "https://komo.ai/", summary: "A search-oriented AI assistant built around quick exploration, summaries, and linked web results.", categories: ["Research", "Assistants"], audience: ["Researchers", "Consultants", "Students"], pricing: "Free / Paid", monthlyVisits: 5200000, recommendation: "Worth including for users specifically shopping AI search alternatives.", searchTerms: ["komo ai", "search ai"] },
    { id: "felo", name: "Felo Search", vendor: "Felo", logoLetter: "F", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://felo.ai/search", summary: "A multilingual AI search product positioned for fast question answering and source-backed exploration.", categories: ["Research", "Translation", "Assistants"], audience: ["Global teams", "Researchers", "Students"], pricing: "Free / Paid", monthlyVisits: 9700000, recommendation: "A practical listing for users who search across languages and want a cleaner answer layer.", searchTerms: ["felo ai", "multilingual search"] },
    { id: "exa", name: "Exa", vendor: "Exa", logoLetter: "E", accent: "linear-gradient(145deg, #1d4ed8, #111827)", url: "https://exa.ai/", summary: "A search and discovery platform oriented toward AI-native retrieval, research, and developer use cases.", categories: ["Research", "Coding", "Assistants"], audience: ["Developers", "Researchers", "Startups"], pricing: "Free / Paid", monthlyVisits: 8400000, recommendation: "High-signal for builder audiences that care about search infrastructure and research APIs.", searchTerms: ["exa ai", "ai search api", "retrieval"] },
    { id: "blackboxai", name: "BLACKBOX AI", vendor: "BLACKBOX AI", logoLetter: "B", accent: "linear-gradient(145deg, #111827, #6366f1)", url: "https://www.blackbox.ai/", summary: "A coding assistant and search surface popular with developers looking for quick code generation and debugging help.", categories: ["Coding", "Assistants", "Research"], audience: ["Developers", "Students", "Technical teams"], pricing: "Freemium", monthlyVisits: 42500000, recommendation: "Useful to compare when coding speed and snippet-oriented help matter more than a premium IDE experience.", searchTerms: ["blackbox", "code ai", "developer ai"] },
    { id: "devin", name: "Devin", vendor: "Cognition", logoLetter: "D", accent: "linear-gradient(145deg, #0f172a, #22c55e)", url: "https://devin.ai/", summary: "An AI software engineering agent positioned around longer-running coding tasks and autonomous execution.", categories: ["Coding", "Automation"], audience: ["Engineering teams", "Startups", "Technical leaders"], pricing: "Paid", monthlyVisits: 6600000, recommendation: "A notable agent entry for teams exploring higher-autonomy engineering workflows.", searchTerms: ["devin ai", "coding agent", "software engineer ai"] },
    { id: "aider", name: "Aider", vendor: "Aider", logoLetter: "A", accent: "linear-gradient(145deg, #334155, #0ea5e9)", url: "https://aider.chat/", summary: "A terminal-first coding assistant built for repository editing, refactors, and code conversations.", categories: ["Coding", "Automation"], audience: ["Developers", "Open-source users", "Power users"], pricing: "Free / Paid", monthlyVisits: 3700000, recommendation: "Great to include for users who prefer terminal-native AI coding workflows over browser tools.", searchTerms: ["aider chat", "terminal coding ai", "repo edit ai"] },
    { id: "claudecode", name: "Claude Code", vendor: "Anthropic", logoLetter: "C", accent: "linear-gradient(145deg, #c26f2e, #7c2d12)", url: "https://claude.com/product/claude-code", summary: "Anthropic's coding-focused product for codebase understanding, editing, and developer assistance.", categories: ["Coding", "Assistants"], audience: ["Developers", "Engineering teams", "Power users"], pricing: "Paid", monthlyVisits: 9100000, recommendation: "A high-interest addition for buyers comparing the new generation of coding agents and copilots.", searchTerms: ["anthropic coding", "claude for coding"] },
    { id: "wixai", name: "Wix AI", vendor: "Wix", logoLetter: "W", accent: "linear-gradient(145deg, #2563eb, #111827)", url: "https://www.wix.com/ai", summary: "Wix's AI layer for website generation, editing assistance, and no-code business site workflows.", categories: ["Design", "Productivity", "Writing"], audience: ["Small businesses", "Creators", "Agencies"], pricing: "Free / Paid", monthlyVisits: 34000000, recommendation: "Strong for users who want practical website production inside a familiar hosted platform.", searchTerms: ["wix ai website builder", "site builder ai"] },
    { id: "durable", name: "Durable", vendor: "Durable", logoLetter: "D", accent: "linear-gradient(145deg, #7c3aed, #ec4899)", url: "https://durable.com/", summary: "An AI website and small-business operating platform built for rapid launch, CRM, and lightweight marketing.", categories: ["Design", "Sales", "Productivity"], audience: ["Small businesses", "Freelancers", "Agencies"], pricing: "Paid", monthlyVisits: 12800000, recommendation: "A good fit when the buyer wants to launch fast and keep website plus operations in one product.", searchTerms: ["durable ai", "business website ai"] },
    { id: "hostingerai", name: "Hostinger AI Website Builder", vendor: "Hostinger", logoLetter: "H", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://www.hostinger.com/ai-website-builder", summary: "A hosted AI website builder aimed at small businesses that want quick setup and bundled infrastructure.", categories: ["Design", "Productivity"], audience: ["Small businesses", "Founders", "Creators"], pricing: "Paid", monthlyVisits: 17400000, recommendation: "Useful where simple deployment and low-friction hosting matter more than design flexibility.", searchTerms: ["hostinger ai", "ai website builder"] },
    { id: "tenweb", name: "10Web", vendor: "10Web", logoLetter: "T", accent: "linear-gradient(145deg, #0ea5e9, #2563eb)", url: "https://10web.io/ai-website-builder/", summary: "A WordPress-oriented AI website builder for faster page generation and managed site operations.", categories: ["Design", "Productivity"], audience: ["Agencies", "Small businesses", "WordPress users"], pricing: "Paid", monthlyVisits: 7100000, recommendation: "A practical listing for buyers who still want WordPress underneath the AI builder layer.", searchTerms: ["10web ai", "wordpress ai builder"] },
    { id: "webflowai", name: "Webflow AI", vendor: "Webflow", logoLetter: "W", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://webflow.com/ai", summary: "AI-assisted creation inside Webflow for website copy, layout acceleration, and faster design iteration.", categories: ["Design", "Writing", "Productivity"], audience: ["Design teams", "Agencies", "Marketers"], pricing: "Free / Paid", monthlyVisits: 19600000, recommendation: "Ideal when teams already trust Webflow and want AI without leaving their production stack.", searchTerms: ["webflow ai", "web design ai"] },
    { id: "shopifymagic", name: "Shopify Magic", vendor: "Shopify", logoLetter: "S", accent: "linear-gradient(145deg, #16a34a, #065f46)", url: "https://www.shopify.com/magic", summary: "Shopify's AI suite for merchants covering product copy, support, and commerce workflow assistance.", categories: ["Sales", "Writing", "Automation"], audience: ["E-commerce teams", "Brands", "Merchants"], pricing: "Free / Paid", monthlyVisits: 22100000, recommendation: "Worth including because commerce buyers often prefer AI embedded in the storefront platform they already use.", searchTerms: ["shopify ai", "ecommerce ai"] },
    { id: "adobepodcast", name: "Adobe Podcast", vendor: "Adobe", logoLetter: "A", accent: "linear-gradient(145deg, #ef4444, #f97316)", url: "https://podcast.adobe.com/", summary: "An AI audio cleanup and recording workspace aimed at creators, podcast teams, and voice-heavy workflows.", categories: ["Audio", "Productivity"], audience: ["Podcasters", "Creators", "Marketing teams"], pricing: "Free / Paid", monthlyVisits: 24900000, recommendation: "A very practical addition because voice cleanup is one of the clearest production AI use cases.", searchTerms: ["audio enhance", "podcast ai", "adobe ai audio"] },
    { id: "captions", name: "Captions", vendor: "Captions", logoLetter: "C", accent: "linear-gradient(145deg, #111827, #ef4444)", url: "https://www.captions.ai/", summary: "An AI video app focused on talking-head content, captions, avatars, and social-ready editing workflows.", categories: ["Video", "Audio", "Productivity"], audience: ["Creators", "Social teams", "Agencies"], pricing: "Freemium", monthlyVisits: 31800000, recommendation: "High-signal for social video teams that care about speed, captions, and mobile-friendly production.", searchTerms: ["captions ai", "video captions", "talking head ai"] },
    { id: "riverside", name: "Riverside", vendor: "Riverside", logoLetter: "R", accent: "linear-gradient(145deg, #0f172a, #8b5cf6)", url: "https://riverside.com/", summary: "A remote recording and editing platform with AI features for podcasts, interviews, and content repurposing.", categories: ["Audio", "Video", "Productivity"], audience: ["Podcasters", "Media teams", "Marketing teams"], pricing: "Freemium", monthlyVisits: 22400000, recommendation: "A strong category entry when high-quality remote recording matters as much as AI assists.", searchTerms: ["riverside fm", "podcast recording ai"] },
    { id: "fliki", name: "Fliki", vendor: "Fliki", logoLetter: "F", accent: "linear-gradient(145deg, #8b5cf6, #ec4899)", url: "https://fliki.ai/", summary: "A text-to-video and text-to-voice product for lightweight social content, explainers, and narrated assets.", categories: ["Video", "Audio", "Writing"], audience: ["Creators", "Marketers", "Small teams"], pricing: "Freemium", monthlyVisits: 16100000, recommendation: "Useful when buyers want an easier path from script to published media without a full studio stack.", searchTerms: ["text to video", "text to speech video"] },
    { id: "playht", name: "PlayHT", vendor: "PlayHT", logoLetter: "P", accent: "linear-gradient(145deg, #2563eb, #ec4899)", url: "https://play.ht/", summary: "A synthetic voice platform for realistic text-to-speech, narration, and voice automation workflows.", categories: ["Audio", "Automation"], audience: ["Developers", "Creators", "Media teams"], pricing: "Freemium", monthlyVisits: 11300000, recommendation: "A strong fit when teams need developer-friendly voice generation beyond simple consumer TTS apps.", searchTerms: ["play ht", "voice ai", "tts api"] },
    { id: "wordtune", name: "Wordtune", vendor: "AI21 Labs", logoLetter: "W", accent: "linear-gradient(145deg, #06b6d4, #2563eb)", url: "https://www.wordtune.com/", summary: "A writing assistant centered on rewriting, summarization, and clarity improvements for daily communication.", categories: ["Writing", "Productivity"], audience: ["Professionals", "Students", "Marketing teams"], pricing: "Freemium", monthlyVisits: 20700000, recommendation: "A practical listing for users who mostly want sentence-level writing help instead of a full AI workspace.", searchTerms: ["rewrite ai", "writing assistant"] },
    { id: "writesonic", name: "Writesonic", vendor: "Writesonic", logoLetter: "W", accent: "linear-gradient(145deg, #f97316, #ef4444)", url: "https://writesonic.com/", summary: "A marketing-oriented AI writing platform for blogs, landing pages, ads, and SEO content workflows.", categories: ["Writing", "Sales", "Productivity"], audience: ["Marketers", "Agencies", "Growth teams"], pricing: "Freemium", monthlyVisits: 21500000, recommendation: "Worth comparing when the primary buying need is high-volume marketing copy and content production.", searchTerms: ["seo writing ai", "marketing copy ai"] }
  ].map((tool) => ({
    ...tool,
    trafficLabel: formatTrafficLabel(tool.monthlyVisits),
    sources: {
      futurepedia: "https://www.futurepedia.io/ai-tools",
      toolify: "https://www.toolify.ai/Best-trending-AI-Tools"
    }
  }));

  const existingIds = new Set(catalog.tools.map((tool) => tool.id));
  extraTools.forEach((tool) => {
    if (!existingIds.has(tool.id)) {
      catalog.tools.push(tool);
      existingIds.add(tool.id);
    }
  });
}());
