window.AI_CATALOG.tools.push(
  {
    id: "scite",
    name: "Scite",
    vendor: "Scite",
    logoLetter: "S",
    accent: "linear-gradient(145deg, #2563eb, #0ea5e9)",
    url: "https://scite.ai/",
    summary: "A research assistant built around citation context, helping users see how papers are supported, disputed, or mentioned.",
    categories: ["Research"],
    audience: ["Researchers", "Students", "Analysts"],
    pricing: "Freemium",
    monthlyVisits: 2300000,
    trafficLabel: "2.3M monthly visits",
    recommendation: "A high-signal tool when your workflow depends on literature quality, not just paper discovery volume.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "elicit",
    name: "Elicit",
    vendor: "Elicit",
    logoLetter: "E",
    accent: "linear-gradient(145deg, #111827, #14b8a6)",
    url: "https://elicit.com/",
    summary: "An AI research workflow tool designed to accelerate paper search, evidence synthesis, and literature review tasks.",
    categories: ["Research", "Productivity"],
    audience: ["Researchers", "Graduate students", "Strategy teams"],
    pricing: "Freemium",
    monthlyVisits: 2900000,
    trafficLabel: "2.9M monthly visits",
    recommendation: "One of the stronger picks if you need research synthesis rather than just another general chat interface.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "scispace",
    name: "SciSpace",
    vendor: "SciSpace",
    logoLetter: "S",
    accent: "linear-gradient(145deg, #7c3aed, #2563eb)",
    url: "https://typeset.io/",
    summary: "A paper reading and research assistance workspace that helps users understand, summarize, and organize academic literature.",
    categories: ["Research"],
    audience: ["Researchers", "Students", "Academic teams"],
    pricing: "Freemium",
    monthlyVisits: 5400000,
    trafficLabel: "5.4M monthly visits",
    recommendation: "A good fit when the team needs a more approachable academic reading surface with built-in explanation support.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "gptzero",
    name: "GPTZero",
    vendor: "GPTZero",
    logoLetter: "G",
    accent: "linear-gradient(145deg, #111827, #f97316)",
    url: "https://gptzero.me/",
    summary: "An AI detection and writing analysis product used across education and editorial review workflows.",
    categories: ["Writing", "Research"],
    audience: ["Educators", "Editors", "Institutions"],
    pricing: "Freemium",
    monthlyVisits: 11700000,
    trafficLabel: "11.7M monthly visits",
    recommendation: "Relevant when stakeholders explicitly need AI-origin detection as part of content governance or review.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "mem",
    name: "Mem",
    vendor: "Mem",
    logoLetter: "M",
    accent: "linear-gradient(145deg, #ec4899, #8b5cf6)",
    url: "https://mem.ai/",
    summary: "An AI-native notes and knowledge workspace aimed at recall, connected context, and lightweight personal organization.",
    categories: ["Productivity", "Writing"],
    audience: ["Founders", "Operators", "Knowledge workers"],
    pricing: "Freemium",
    monthlyVisits: 1700000,
    trafficLabel: "1.7M monthly visits",
    recommendation: "A credible option if you want your note system to behave more like an AI memory layer than a blank document tool.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "taskade",
    name: "Taskade",
    vendor: "Taskade",
    logoLetter: "T",
    accent: "linear-gradient(145deg, #14b8a6, #2563eb)",
    url: "https://www.taskade.com/",
    summary: "A collaborative productivity tool combining tasks, docs, mind maps, and AI agents into a flexible team workspace.",
    categories: ["Productivity", "Automation", "Writing"],
    audience: ["Small teams", "Operators", "Founders"],
    pricing: "Freemium",
    monthlyVisits: 2400000,
    trafficLabel: "2.4M monthly visits",
    recommendation: "Worth adding when your team wants lightweight collaboration plus AI help without committing to a heavier suite.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "coda",
    name: "Coda AI",
    vendor: "Coda",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #ef4444, #f59e0b)",
    url: "https://coda.io/",
    summary: "A doc-database hybrid workspace with AI assistance for operating systems, plans, trackers, and internal workflows.",
    categories: ["Productivity", "Automation"],
    audience: ["Ops teams", "PMs", "Startups"],
    pricing: "Free / Paid",
    monthlyVisits: 6100000,
    trafficLabel: "6.1M monthly visits",
    recommendation: "A strong fit if the team wants AI layered onto structured docs and operational systems rather than simple notes.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "clickup",
    name: "ClickUp AI",
    vendor: "ClickUp",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #7c3aed, #ec4899)",
    url: "https://clickup.com/ai",
    summary: "A project management platform with AI features for planning, writing, summaries, and workflow execution inside team operations.",
    categories: ["Productivity", "Writing", "Automation"],
    audience: ["Operations teams", "PMs", "Agencies"],
    pricing: "Paid",
    monthlyVisits: 29000000,
    trafficLabel: "29.0M monthly visits",
    recommendation: "A practical listing when buyers are already shopping project suites and want AI where work already lives.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "krea",
    name: "Krea",
    vendor: "Krea",
    logoLetter: "K",
    accent: "linear-gradient(145deg, #111827, #06b6d4)",
    url: "https://www.krea.ai/",
    summary: "A visual AI creation platform geared toward real-time image generation, upscaling, and creative experimentation.",
    categories: ["Design"],
    audience: ["Designers", "Creators", "Art directors"],
    pricing: "Freemium",
    monthlyVisits: 14700000,
    trafficLabel: "14.7M monthly visits",
    recommendation: "A high-signal creative pick if speed and live visual iteration are more important than template workflows.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "clipdrop",
    name: "Clipdrop",
    vendor: "Jasper",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #2563eb, #8b5cf6)",
    url: "https://clipdrop.co/",
    summary: "An image editing toolkit covering background removal, cleanup, relighting, generation, and creative asset refinement.",
    categories: ["Design"],
    audience: ["Designers", "Marketers", "E-commerce teams"],
    pricing: "Freemium",
    monthlyVisits: 8800000,
    trafficLabel: "8.8M monthly visits",
    recommendation: "Very useful when your workflow is less about full image generation and more about fast visual cleanup and edits.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "removebg",
    name: "remove.bg",
    vendor: "Canva",
    logoLetter: "R",
    accent: "linear-gradient(145deg, #0ea5e9, #14b8a6)",
    url: "https://www.remove.bg/",
    summary: "A focused background removal product that remains widely used because it solves one repetitive image task extremely well.",
    categories: ["Design"],
    audience: ["E-commerce teams", "Marketers", "Designers"],
    pricing: "Freemium",
    monthlyVisits: 32000000,
    trafficLabel: "32.0M monthly visits",
    recommendation: "A must-have utility listing because buyers still search for single-purpose, production-reliable image cleanup tools.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "pixlr",
    name: "Pixlr",
    vendor: "Pixlr",
    logoLetter: "P",
    accent: "linear-gradient(145deg, #111827, #10b981)",
    url: "https://pixlr.com/",
    summary: "A browser-based image editing suite with AI features that appeals to users needing practical design work without full desktop tools.",
    categories: ["Design"],
    audience: ["Creators", "Marketers", "Small businesses"],
    pricing: "Freemium",
    monthlyVisits: 13700000,
    trafficLabel: "13.7M monthly visits",
    recommendation: "Useful when users want something more capable than a generator but lighter than a full professional editor.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "cutoutpro",
    name: "Cutout.Pro",
    vendor: "Cutout.Pro",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #2563eb, #0f172a)",
    url: "https://www.cutout.pro/",
    summary: "An AI visual editing platform that packages background removal, enhancement, photo animation, and utility-style image tools.",
    categories: ["Design", "Video"],
    audience: ["E-commerce teams", "Creators", "Editors"],
    pricing: "Freemium",
    monthlyVisits: 9300000,
    trafficLabel: "9.3M monthly visits",
    recommendation: "A useful inclusion for buyers comparing practical image utilities rather than pure generative art products.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "opusclip",
    name: "OpusClip",
    vendor: "OpusClip",
    logoLetter: "O",
    accent: "linear-gradient(145deg, #f97316, #ef4444)",
    url: "https://www.opus.pro/",
    summary: "A short-form video repurposing platform designed to turn long content into social-ready clips with AI assistance.",
    categories: ["Video", "Productivity"],
    audience: ["Creators", "Media teams", "Marketers"],
    pricing: "Freemium",
    monthlyVisits: 7600000,
    trafficLabel: "7.6M monthly visits",
    recommendation: "High-signal for content teams because repurposing long video into clips is a durable, production-grade use case.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "filmora",
    name: "Wondershare Filmora",
    vendor: "Wondershare",
    logoLetter: "F",
    accent: "linear-gradient(145deg, #14b8a6, #06b6d4)",
    url: "https://filmora.wondershare.com/",
    summary: "A mainstream video editing product that has added AI features for creators who want familiar editing with modern assists.",
    categories: ["Video"],
    audience: ["Creators", "YouTubers", "Small teams"],
    pricing: "Paid",
    monthlyVisits: 24600000,
    trafficLabel: "24.6M monthly visits",
    recommendation: "A sensible addition because many users still prefer an editor-first workflow with AI features added on top.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "speechify",
    name: "Speechify",
    vendor: "Speechify",
    logoLetter: "S",
    accent: "linear-gradient(145deg, #2563eb, #14b8a6)",
    url: "https://speechify.com/",
    summary: "A popular text-to-speech product built around reading acceleration, accessibility, and voice-based content consumption.",
    categories: ["Audio", "Productivity"],
    audience: ["Students", "Professionals", "Accessibility users"],
    pricing: "Freemium",
    monthlyVisits: 9600000,
    trafficLabel: "9.6M monthly visits",
    recommendation: "A strong listing for users specifically shopping high-usage read-aloud and listening-first productivity tools.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "adobeexpress",
    name: "Adobe Express",
    vendor: "Adobe",
    logoLetter: "A",
    accent: "linear-gradient(145deg, #ef4444, #7c3aed)",
    url: "https://www.adobe.com/express/",
    summary: "A lightweight Adobe creation workspace for social graphics, videos, documents, and AI-assisted creative tasks.",
    categories: ["Design", "Video", "Writing"],
    audience: ["Marketers", "Small businesses", "Creators"],
    pricing: "Freemium",
    monthlyVisits: 38000000,
    trafficLabel: "38.0M monthly visits",
    recommendation: "A high-signal mainstream option when users want broad creative output inside a trusted brand ecosystem.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  }
);
