(function () {
  const catalog = window.AI_CATALOG;
  if (!catalog || !Array.isArray(catalog.tools)) {
    return;
  }

  function formatTrafficLabel(monthlyVisits) {
    if (monthlyVisits >= 1000000000) {
      return `${(monthlyVisits / 1000000000).toFixed(1)}B monthly visits`;
    }
    return `${(monthlyVisits / 1000000).toFixed(1)}M monthly visits`;
  }

  const extraTools = [
    { id: "manus", name: "Manus", vendor: "Monica", logoLetter: "M", accent: "linear-gradient(145deg, #0f172a, #2563eb)", url: "https://manus.im/", summary: "A high-interest AI agent product for delegating multi-step research, planning, and operational tasks.", categories: ["Assistants", "Automation", "Research"], audience: ["Operators", "Founders", "Power users"], pricing: "Free / Paid", monthlyVisits: 32200000, recommendation: "A strong addition because agent-native products are now a core discovery category.", searchTerms: ["manus ai", "general agent", "task agent"] },
    { id: "phind", name: "Phind", vendor: "Phind", logoLetter: "P", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://www.phind.com/", summary: "A developer-first answer engine for coding questions, technical search, and source-backed explanations.", categories: ["Coding", "Research", "Assistants"], audience: ["Developers", "Students", "Technical founders"], pricing: "Free / Paid", monthlyVisits: 12600000, recommendation: "A practical coding search inclusion for users who prefer answer engines over general chat.", searchTerms: ["developer search", "coding search ai", "technical answer engine"] },
    { id: "langsmith", name: "LangSmith", vendor: "LangChain", logoLetter: "L", accent: "linear-gradient(145deg, #16a34a, #0f766e)", url: "https://www.langchain.com/langsmith", summary: "An observability and evaluation platform for LLM apps, agents, and production prompt systems.", categories: ["Coding", "Automation", "Research"], audience: ["AI engineers", "Developers", "Platform teams"], pricing: "Paid", monthlyVisits: 2800000, recommendation: "A useful listing for teams moving from demos into serious agent and LLM operations.", searchTerms: ["llm observability", "agent evaluation", "prompt ops"] },
    { id: "pinecone", name: "Pinecone", vendor: "Pinecone", logoLetter: "P", accent: "linear-gradient(145deg, #16a34a, #22c55e)", url: "https://www.pinecone.io/", summary: "A vector database platform heavily used in retrieval, search, and enterprise AI application stacks.", categories: ["Coding", "Research", "Automation"], audience: ["Developers", "AI teams", "Enterprises"], pricing: "Paid", monthlyVisits: 3600000, recommendation: "Important for builder audiences comparing retrieval and RAG infrastructure.", searchTerms: ["vector database", "rag infrastructure", "retrieval database"] },
    { id: "hixai", name: "HIX.AI", vendor: "HIX.AI", logoLetter: "H", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://hix.ai/", summary: "A broad writing and productivity suite for blogs, email, rewriting, and browser-based AI assistance.", categories: ["Writing", "Productivity", "Sales"], audience: ["Marketers", "Students", "Small businesses"], pricing: "Freemium", monthlyVisits: 9400000, recommendation: "A strong suite-style listing for buyers comparing broad writing platforms.", searchTerms: ["writing suite ai", "browser writer ai", "email writing ai"] },
    { id: "janitorai", name: "JanitorAI", vendor: "JanitorAI", logoLetter: "J", accent: "linear-gradient(145deg, #111827, #7c3aed)", url: "https://janitorai.com/", summary: "A very high-traffic character and conversational AI platform built around custom personalities and interactive chat.", categories: ["Assistants", "Writing"], audience: ["Consumers", "Roleplay users", "Community users"], pricing: "Free / Paid", monthlyVisits: 29600000, recommendation: "Relevant because character-style chat remains one of the highest-volume AI consumer categories.", searchTerms: ["character chat", "roleplay ai", "persona chat"] },
    { id: "civitai", name: "Civitai", vendor: "Civitai", logoLetter: "C", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://civitai.com/", summary: "A major community hub for image-generation models, prompts, and creative workflows.", categories: ["Design", "Research"], audience: ["Creators", "Designers", "AI art users"], pricing: "Free / Paid", monthlyVisits: 18600000, recommendation: "A meaningful addition because model-community ecosystems still drive image tool discovery.", searchTerms: ["stable diffusion models", "prompt sharing", "image model hub"] },
    { id: "novelai", name: "NovelAI", vendor: "NovelAI", logoLetter: "N", accent: "linear-gradient(145deg, #7c3aed, #ec4899)", url: "https://novelai.net/", summary: "A fiction and image-oriented AI platform with a strong creative writing and storytelling audience.", categories: ["Writing", "Design"], audience: ["Authors", "Roleplay users", "Creative writers"], pricing: "Paid", monthlyVisits: 5100000, recommendation: "A notable listing because fiction-first AI buyers are a distinct and durable segment.", searchTerms: ["story writing ai", "fiction generation", "anime image ai"] },
    { id: "lovo", name: "LOVO AI", vendor: "LOVO", logoLetter: "L", accent: "linear-gradient(145deg, #0ea5e9, #2563eb)", url: "https://lovo.ai/", summary: "A voice generation and AI video platform popular for marketing, training, and creator narration.", categories: ["Audio", "Video"], audience: ["Creators", "Marketers", "Training teams"], pricing: "Freemium", monthlyVisits: 6400000, recommendation: "A practical voice-and-video entry for content teams that want broad media output.", searchTerms: ["voice generator", "voiceover ai", "genny ai"] },
    { id: "podcastle", name: "Podcastle", vendor: "Podcastle", logoLetter: "P", accent: "linear-gradient(145deg, #0f172a, #ef4444)", url: "https://podcastle.ai/", summary: "A creator platform for podcast recording, editing, AI voice, and lightweight media production.", categories: ["Audio", "Video", "Productivity"], audience: ["Podcasters", "Creators", "Marketing teams"], pricing: "Freemium", monthlyVisits: 7300000, recommendation: "Useful where teams want AI media production around podcasts and narrated content.", searchTerms: ["podcast editor ai", "voiceover studio", "audio creator ai"] },
    { id: "voicemod", name: "Voicemod", vendor: "Voicemod", logoLetter: "V", accent: "linear-gradient(145deg, #2563eb, #ec4899)", url: "https://www.voicemod.net/", summary: "A consumer voice transformation product with AI voice features for creators, streamers, and interactive content.", categories: ["Audio"], audience: ["Creators", "Streamers", "Consumers"], pricing: "Freemium", monthlyVisits: 12000000, recommendation: "A good addition because creator audio categories extend beyond pure narration and transcription.", searchTerms: ["voice changer ai", "streamer voice ai"] },
    { id: "typecast", name: "Typecast", vendor: "Typecast", logoLetter: "T", accent: "linear-gradient(145deg, #14b8a6, #2563eb)", url: "https://typecast.ai/", summary: "A voice and character content platform for expressive TTS, avatar media, and scripted output.", categories: ["Audio", "Video"], audience: ["Creators", "Marketers", "Studios"], pricing: "Freemium", monthlyVisits: 3600000, recommendation: "A useful listing for teams that need more expressive synthetic voice than generic TTS offers.", searchTerms: ["expressive tts", "voice character ai", "avatar voice ai"] },
    { id: "did", name: "D-ID", vendor: "D-ID", logoLetter: "D", accent: "linear-gradient(145deg, #0f172a, #14b8a6)", url: "https://www.d-id.com/", summary: "A talking-avatar platform for presentations, explainers, training, and synthetic spokesperson content.", categories: ["Video", "Audio"], audience: ["Enterprises", "Training teams", "Marketing teams"], pricing: "Paid", monthlyVisits: 4700000, recommendation: "A category staple for buyers evaluating avatar video beyond social creator tools.", searchTerms: ["avatar video", "talking photo ai", "spokesperson ai"] },
    { id: "colossyan", name: "Colossyan", vendor: "Colossyan", logoLetter: "C", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://www.colossyan.com/", summary: "An AI video platform built around workplace training, internal communications, and instructional content.", categories: ["Video", "Productivity"], audience: ["L&D teams", "Enterprises", "Operations teams"], pricing: "Paid", monthlyVisits: 2100000, recommendation: "Strong for professional buyers who care about training and internal comms more than creator content.", searchTerms: ["training video ai", "learning video ai", "workplace video ai"] },
    { id: "elai", name: "Elai.io", vendor: "Elai", logoLetter: "E", accent: "linear-gradient(145deg, #8b5cf6, #2563eb)", url: "https://elai.io/", summary: "An avatar and AI video creation tool for explainers, education, and polished presentation-style media.", categories: ["Video", "Productivity"], audience: ["Education teams", "Marketers", "Enterprises"], pricing: "Freemium", monthlyVisits: 2400000, recommendation: "A credible addition for buyers comparing the business-avatar video segment.", searchTerms: ["ai presenter", "avatar presentation ai", "explainer video ai"] },
    { id: "akool", name: "AKOOL", vendor: "AKOOL", logoLetter: "A", accent: "linear-gradient(145deg, #2563eb, #f97316)", url: "https://akool.com/", summary: "An AI content suite for avatars, face swaps, translation, and synthetic media production.", categories: ["Video", "Audio", "Translation"], audience: ["Marketing teams", "Agencies", "Global teams"], pricing: "Paid", monthlyVisits: 3400000, recommendation: "Useful when teams want multiple synthetic media workflows inside one platform.", searchTerms: ["face swap ai", "avatar suite", "video translation ai"] },
    { id: "insmind", name: "insMind", vendor: "insMind", logoLetter: "I", accent: "linear-gradient(145deg, #16a34a, #2563eb)", url: "https://www.insmind.com/", summary: "A commerce-friendly image editing tool for backgrounds, product visuals, and marketing-ready assets.", categories: ["Design", "Sales"], audience: ["E-commerce teams", "Marketers", "Small businesses"], pricing: "Freemium", monthlyVisits: 9400000, recommendation: "A strong practical addition because product-photo editing remains a high-intent AI job.", searchTerms: ["product photo ai", "background edit ai", "ecommerce image ai"] },
    { id: "dzine", name: "Dzine", vendor: "Dzine", logoLetter: "D", accent: "linear-gradient(145deg, #111827, #ec4899)", url: "https://www.dzine.ai/", summary: "A visual creation platform for images, design ideation, and fast concept exploration.", categories: ["Design"], audience: ["Designers", "Creators", "Art directors"], pricing: "Freemium", monthlyVisits: 3900000, recommendation: "Useful for buyers who want a design-led image workflow rather than a generic model playground.", searchTerms: ["dzine ai", "design image ai", "visual ideation ai"] },
    { id: "bardeen", name: "Bardeen", vendor: "Bardeen", logoLetter: "B", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://www.bardeen.ai/", summary: "A browser and workflow automation product for GTM, operations, and repetitive knowledge-work tasks.", categories: ["Automation", "Productivity", "Sales"], audience: ["Ops teams", "Sales teams", "Growth teams"], pricing: "Freemium", monthlyVisits: 3200000, recommendation: "A smart inclusion because many users want AI plus automation rather than AI chat alone.", searchTerms: ["browser automation ai", "workflow automation ai", "sales automation ai"] },
    { id: "motion", name: "Motion", vendor: "Motion", logoLetter: "M", accent: "linear-gradient(145deg, #111827, #2563eb)", url: "https://www.usemotion.com/", summary: "A scheduling and productivity tool that uses AI to organize calendars, tasks, and planning priorities.", categories: ["Productivity", "Automation"], audience: ["Founders", "Operators", "Busy professionals"], pricing: "Paid", monthlyVisits: 7100000, recommendation: "A good fit for users who want AI to manage time and planning rather than content generation.", searchTerms: ["calendar ai", "task scheduling ai", "time management ai"] },
    { id: "glasp", name: "Glasp", vendor: "Glasp", logoLetter: "G", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://glasp.co/", summary: "A reading, highlighting, and knowledge capture tool with AI support for summarization and discovery.", categories: ["Research", "Productivity"], audience: ["Students", "Researchers", "Knowledge workers"], pricing: "Freemium", monthlyVisits: 2200000, recommendation: "Useful for users whose AI workflow begins with reading and note capture rather than pure chat.", searchTerms: ["web highlight ai", "reading assistant", "knowledge capture ai"] },
    { id: "augmentcode", name: "Augment Code", vendor: "Augment", logoLetter: "A", accent: "linear-gradient(145deg, #111827, #2563eb)", url: "https://www.augmentcode.com/", summary: "An AI software development platform built around code agents that understand an entire codebase instead of isolated files.", categories: ["Coding", "Productivity", "Research"], audience: ["Developers", "Engineering teams", "Technical founders"], pricing: "Paid", monthlyVisits: 2600000, recommendation: "A strong addition for teams comparing serious code agents rather than lighter autocomplete tools.", searchTerms: ["code agent", "codebase context ai", "software agent"] },
    { id: "browseruse", name: "Browser Use", vendor: "Browser Use", logoLetter: "B", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://browser-use.com/", summary: "An open browser automation platform that lets AI agents operate websites, forms, and multi-step web workflows.", categories: ["Automation", "Coding", "Research"], audience: ["Developers", "Operators", "Automation builders"], pricing: "Free / Paid", monthlyVisits: 3900000, recommendation: "Useful because browser-native AI agents are becoming a real buyer category, not just a developer experiment.", searchTerms: ["browser automation", "web agent", "computer use browser"] },
    { id: "sider", name: "Sider", vendor: "Sider", logoLetter: "S", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://sider.ai/", summary: "A browser-side AI workspace for reading, writing, summarizing, translating, and quick research across the web.", categories: ["Assistants", "Productivity", "Writing"], audience: ["General users", "Students", "Knowledge workers"], pricing: "Freemium", monthlyVisits: 21400000, recommendation: "A practical inclusion for users who want AI available as a persistent browser layer instead of a separate app.", searchTerms: ["browser ai assistant", "sidebar ai", "web reading assistant"] },
    { id: "tactiq", name: "Tactiq", vendor: "Tactiq", logoLetter: "T", accent: "linear-gradient(145deg, #f97316, #2563eb)", url: "https://tactiq.io/", summary: "An AI note taker for Google Meet, Zoom, and Teams that captures live transcripts, summaries, and follow-up actions.", categories: ["Meetings", "Productivity", "Writing"], audience: ["Managers", "Sales teams", "Recruiters", "Operators"], pricing: "Freemium", monthlyVisits: 5100000, recommendation: "A solid addition because meeting capture is still one of the cleanest, highest-intent AI jobs for teams.", searchTerms: ["meeting notes ai", "meeting summary ai", "meeting transcript ai"] },
    { id: "fyxer", name: "Fyxer AI", vendor: "Fyxer", logoLetter: "F", accent: "linear-gradient(145deg, #111827, #14b8a6)", url: "https://www.fyxer.com/", summary: "An inbox assistant that organizes email, drafts replies in your tone, and turns meetings into usable notes.", categories: ["Productivity", "Meetings", "Writing"], audience: ["Executives", "Founders", "Busy professionals"], pricing: "Paid", monthlyVisits: 2300000, recommendation: "A useful pick for buyers who care more about inbox throughput and follow-up than generic chatbot output.", searchTerms: ["email assistant", "inbox ai", "meeting notes assistant"] },
    { id: "wisprflow", name: "Wispr Flow", vendor: "Wispr", logoLetter: "W", accent: "linear-gradient(145deg, #14b8a6, #2563eb)", url: "https://wisprflow.ai/", summary: "A voice dictation tool focused on turning speech into clean, usable writing across everyday workflows.", categories: ["Writing", "Productivity"], audience: ["Founders", "Operators", "Writers"], pricing: "Free / Paid", monthlyVisits: 3400000, recommendation: "Worth adding because voice-first input is becoming a meaningful alternative to keyboard-first AI workflows.", searchTerms: ["voice dictation ai", "speech to text writing", "voice typing ai"] },
    { id: "lovart", name: "Lovart", vendor: "Lovart", logoLetter: "L", accent: "linear-gradient(145deg, #ec4899, #f97316)", url: "https://www.lovart.ai/", summary: "An AI design agent positioned around automating creative workflows from logos and social graphics to broader campaign production.", categories: ["Design", "Productivity"], audience: ["Designers", "Marketers", "Creative teams"], pricing: "Freemium", monthlyVisits: 4200000, recommendation: "A good addition for users evaluating the next wave of design agents rather than prompt-only image tools.", searchTerms: ["design agent", "creative workflow ai", "marketing design ai"] }
  ].map((tool) => ({
    ...tool,
    trafficLabel: formatTrafficLabel(tool.monthlyVisits),
    sources: {
      futurepedia: "https://www.futurepedia.io/ai-tools",
      toolify: "https://www.toolify.ai/Best-trending-AI-Tools"
    }
  }));

  const existingIds = new Set(catalog.tools.map((tool) => tool.id));
  extraTools.forEach((tool) => {
    if (!existingIds.has(tool.id)) {
      catalog.tools.push(tool);
      existingIds.add(tool.id);
    }
  });
}());
