window.AI_CATALOG.tools.push(
  {
    id: "tabnine",
    name: "Tabnine",
    vendor: "Tabnine",
    logoLetter: "T",
    accent: "linear-gradient(145deg, #2563eb, #06b6d4)",
    url: "https://www.tabnine.com/",
    summary: "An established enterprise-friendly AI coding assistant with a longer history in completion and team deployment workflows.",
    categories: ["Coding"],
    audience: ["Engineering teams", "Security-conscious buyers", "Developers"],
    pricing: "Freemium",
    monthlyVisits: 2200000,
    trafficLabel: "2.2M monthly visits",
    recommendation: "Most relevant when privacy posture, enterprise packaging, and conservative rollout matter as much as raw model power.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "sourcegraph",
    name: "Sourcegraph Cody",
    vendor: "Sourcegraph",
    logoLetter: "S",
    accent: "linear-gradient(145deg, #f97316, #8b5cf6)",
    url: "https://sourcegraph.com/cody",
    summary: "A repo-aware coding assistant aimed at larger codebases, search-heavy engineering work, and enterprise developer teams.",
    categories: ["Coding", "Research"],
    audience: ["Platform teams", "Enterprise developers", "Technical leads"],
    pricing: "Free / Paid",
    monthlyVisits: 6100000,
    trafficLabel: "6.1M monthly visits",
    recommendation: "A good fit when code search, context across large repos, and engineering knowledge retrieval are central requirements.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "continue",
    name: "Continue",
    vendor: "Continue",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #111827, #10b981)",
    url: "https://www.continue.dev/",
    summary: "An open and developer-friendly AI coding assistant framework for teams that want more control over models and IDE behavior.",
    categories: ["Coding"],
    audience: ["Developers", "Open-source leaning teams", "Infra-conscious builders"],
    pricing: "Free / Paid",
    monthlyVisits: 1800000,
    trafficLabel: "1.8M monthly visits",
    recommendation: "A meaningful option when flexibility, model choice, and local control matter more than turnkey polish alone.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "intercom",
    name: "Intercom Fin",
    vendor: "Intercom",
    logoLetter: "I",
    accent: "linear-gradient(145deg, #2563eb, #60a5fa)",
    url: "https://www.intercom.com/ai",
    summary: "An AI-first customer support platform designed for support automation, agent assistance, and scalable service workflows.",
    categories: ["Automation", "Sales", "Productivity"],
    audience: ["Support teams", "Customer success", "B2B SaaS"],
    pricing: "Paid",
    monthlyVisits: 16000000,
    trafficLabel: "16.0M monthly visits",
    recommendation: "A serious option when the team wants AI to resolve support volume inside a mature customer messaging stack.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "granola",
    name: "Granola",
    vendor: "Granola",
    logoLetter: "G",
    accent: "linear-gradient(145deg, #f97316, #f59e0b)",
    url: "https://www.granola.ai/",
    summary: "A lightweight AI meeting assistant focused on turning conversations into cleaner notes without adding a heavy collaboration layer.",
    categories: ["Meetings", "Productivity"],
    audience: ["Founders", "Operators", "PMs"],
    pricing: "Freemium",
    monthlyVisits: 2100000,
    trafficLabel: "2.1M monthly visits",
    recommendation: "A strong fit if you want meeting capture that feels lighter and more personal than enterprise meeting suites.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "lindy",
    name: "Lindy",
    vendor: "Lindy",
    logoLetter: "L",
    accent: "linear-gradient(145deg, #ec4899, #8b5cf6)",
    url: "https://www.lindy.ai/",
    summary: "An AI agent automation platform aimed at operational workflows, inbox handling, scheduling, and agent-style business tasks.",
    categories: ["Automation", "Productivity"],
    audience: ["Operators", "Founders", "Small teams"],
    pricing: "Freemium",
    monthlyVisits: 4100000,
    trafficLabel: "4.1M monthly visits",
    recommendation: "Worth exploring if your team wants agent-like delegation without building an automation stack from scratch.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "make",
    name: "Make",
    vendor: "Make",
    logoLetter: "M",
    accent: "linear-gradient(145deg, #7c3aed, #2563eb)",
    url: "https://www.make.com/",
    summary: "A visual automation platform that pairs well with AI workflows when teams need more branching logic and orchestration depth.",
    categories: ["Automation", "Productivity"],
    audience: ["Ops teams", "Automation builders", "Agencies"],
    pricing: "Freemium",
    monthlyVisits: 19000000,
    trafficLabel: "19.0M monthly visits",
    recommendation: "A strong Zapier comparison if your automations are more complex and need richer scenario building.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "n8n",
    name: "n8n",
    vendor: "n8n",
    logoLetter: "N",
    accent: "linear-gradient(145deg, #ef4444, #f97316)",
    url: "https://n8n.io/",
    summary: "An automation platform popular with technical teams that want more control, self-hosting options, and AI-native orchestration flexibility.",
    categories: ["Automation", "Coding", "Productivity"],
    audience: ["Developers", "Ops engineers", "Technical teams"],
    pricing: "Free / Paid",
    monthlyVisits: 7400000,
    trafficLabel: "7.4M monthly visits",
    recommendation: "A high-signal pick when your team wants automation power closer to engineering workflows than to pure no-code tooling.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "readai",
    name: "Read AI",
    vendor: "Read AI",
    logoLetter: "R",
    accent: "linear-gradient(145deg, #0ea5e9, #14b8a6)",
    url: "https://www.read.ai/",
    summary: "A meeting intelligence layer built for summaries, action items, and post-meeting operational follow-through.",
    categories: ["Meetings", "Productivity"],
    audience: ["Managers", "Ops teams", "Revenue teams"],
    pricing: "Freemium",
    monthlyVisits: 3100000,
    trafficLabel: "3.1M monthly visits",
    recommendation: "Best when your problem is not recording meetings, but extracting follow-through value after them.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "tldv",
    name: "tl;dv",
    vendor: "tl;dv",
    logoLetter: "T",
    accent: "linear-gradient(145deg, #111827, #8b5cf6)",
    url: "https://tldv.io/",
    summary: "A meeting recorder and summarizer that helps teams capture discussions, surface action items, and share clips quickly.",
    categories: ["Meetings", "Productivity"],
    audience: ["Remote teams", "Sales", "Customer success"],
    pricing: "Freemium",
    monthlyVisits: 2400000,
    trafficLabel: "2.4M monthly visits",
    recommendation: "A practical pick when searchable meeting memory and quick knowledge handoff matter to the team.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "fellow",
    name: "Fellow",
    vendor: "Fellow",
    logoLetter: "F",
    accent: "linear-gradient(145deg, #2563eb, #6366f1)",
    url: "https://fellow.app/",
    summary: "A meeting and management workspace that brings agendas, AI notes, and follow-up discipline into one operating layer.",
    categories: ["Meetings", "Productivity"],
    audience: ["Managers", "Leadership teams", "Operators"],
    pricing: "Freemium",
    monthlyVisits: 2200000,
    trafficLabel: "2.2M monthly visits",
    recommendation: "Most useful when the goal is not just note capture but stronger management cadence and team accountability.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "superhuman",
    name: "Superhuman",
    vendor: "Superhuman",
    logoLetter: "S",
    accent: "linear-gradient(145deg, #111827, #ec4899)",
    url: "https://superhuman.com/",
    summary: "An AI-enhanced email product focused on speed, prioritization, and high-performance inbox workflows.",
    categories: ["Productivity", "Writing"],
    audience: ["Executives", "Founders", "Revenue teams"],
    pricing: "Paid",
    monthlyVisits: 2500000,
    trafficLabel: "2.5M monthly visits",
    recommendation: "A sensible upgrade when the inbox is a real operating surface and AI needs to speed decisions, not just draft copy.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "characterai",
    name: "Character.AI",
    vendor: "Character.AI",
    logoLetter: "C",
    accent: "linear-gradient(145deg, #7c3aed, #ec4899)",
    url: "https://character.ai/",
    summary: "A consumer AI product centered on personality-led conversation, roleplay, and engagement-first assistant experiences.",
    categories: ["Assistants", "Writing"],
    audience: ["Consumers", "Creative users", "Early adopters"],
    pricing: "Freemium",
    monthlyVisits: 120000000,
    trafficLabel: "120.0M monthly visits",
    recommendation: "Relevant when the product comparison is about conversational style and engagement rather than business workflow utility.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "poe",
    name: "Poe",
    vendor: "Quora",
    logoLetter: "P",
    accent: "linear-gradient(145deg, #8b5cf6, #2563eb)",
    url: "https://poe.com/",
    summary: "A multi-model AI chat surface that lets users compare models, bots, and specialized assistants in one place.",
    categories: ["Assistants", "Research"],
    audience: ["Power users", "Researchers", "Model shoppers"],
    pricing: "Freemium",
    monthlyVisits: 60000000,
    trafficLabel: "60.0M monthly visits",
    recommendation: "One of the better consumer-facing surfaces if your goal is to compare many models without juggling separate products.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "qwen",
    name: "Qwen Chat",
    vendor: "Alibaba",
    logoLetter: "Q",
    accent: "linear-gradient(145deg, #2563eb, #0f172a)",
    url: "https://chat.qwen.ai/",
    summary: "A high-visibility assistant product tied to Alibaba's Qwen model family with growing reach across reasoning and multimodal tasks.",
    categories: ["Assistants", "Research", "Coding"],
    audience: ["Power users", "Developers", "Researchers"],
    pricing: "Free / Paid",
    monthlyVisits: 90000000,
    trafficLabel: "90.0M monthly visits",
    recommendation: "A meaningful comparison point if your team wants another major model family beyond the usual US-first products.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "monica",
    name: "Monica",
    vendor: "Monica",
    logoLetter: "M",
    accent: "linear-gradient(145deg, #2563eb, #06b6d4)",
    url: "https://monica.im/",
    summary: "A browser-native AI assistant positioned around all-site assistance, reading, summarization, and day-to-day knowledge work.",
    categories: ["Assistants", "Productivity", "Research"],
    audience: ["Knowledge workers", "Researchers", "General users"],
    pricing: "Freemium",
    monthlyVisits: 22000000,
    trafficLabel: "22.0M monthly visits",
    recommendation: "Useful when the assistant needs to travel with you across the web instead of living in one standalone chat product.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  },
  {
    id: "youcom",
    name: "You.com",
    vendor: "You.com",
    logoLetter: "Y",
    accent: "linear-gradient(145deg, #111827, #2563eb)",
    url: "https://you.com/",
    summary: "A search-first AI assistant product blending web retrieval, answer generation, and workflow-friendly research output.",
    categories: ["Assistants", "Research"],
    audience: ["Researchers", "Analysts", "Search-heavy users"],
    pricing: "Free / Paid",
    monthlyVisits: 13000000,
    trafficLabel: "13.0M monthly visits",
    recommendation: "Worth evaluating when web retrieval quality matters and the team prefers a search-native interface.",
    sources: { futurepedia: "https://www.futurepedia.io/ai-tools", toolify: "https://www.toolify.ai/Best-trending-AI-Tools" }
  }
);
