(function () {
  const catalog = window.AI_CATALOG;
  if (!catalog || !Array.isArray(catalog.tools)) {
    return;
  }

  function formatTrafficLabel(monthlyVisits) {
    if (monthlyVisits >= 1000000000) {
      return `${(monthlyVisits / 1000000000).toFixed(1)}B monthly visits`;
    }
    return `${(monthlyVisits / 1000000).toFixed(1)}M monthly visits`;
  }

  const existingIds = new Set(catalog.tools.map((tool) => tool.id));
  const sharedSources = {
    futurepedia: "https://www.futurepedia.io/ai-tools",
    toolify: "https://www.toolify.ai/Best-trending-AI-Tools"
  };

  function addTools(batch) {
    batch.forEach((tool) => {
      if (existingIds.has(tool.id)) {
        return;
      }
      catalog.tools.push({
        ...tool,
        trafficLabel: formatTrafficLabel(tool.monthlyVisits),
        sources: sharedSources
      });
      existingIds.add(tool.id);
    });
  }

  addTools([
    { id: "openevidence", name: "OpenEvidence", vendor: "OpenEvidence", logoLetter: "O", accent: "linear-gradient(145deg, #0f172a, #2563eb)", url: "https://www.openevidence.com/", summary: "A clinical AI search and evidence assistant built to help doctors surface studies, guidelines, and medical answers quickly.", categories: ["Research", "Assistants"], audience: ["Clinicians", "Healthcare teams", "Researchers"], pricing: "Free / Paid", monthlyVisits: 14100000, recommendation: "A high-heat vertical AI product that expands the directory beyond general-purpose chat.", searchTerms: ["clinical ai", "medical evidence search", "doctor ai assistant"] },
    { id: "limitless", name: "Limitless", vendor: "Limitless", logoLetter: "L", accent: "linear-gradient(145deg, #111827, #14b8a6)", url: "https://www.limitless.ai/", summary: "A memory assistant that captures meetings, conversations, and context so users can search their day later.", categories: ["Productivity", "Meetings", "Research"], audience: ["Founders", "Operators", "Executives"], pricing: "Paid", monthlyVisits: 6800000, recommendation: "A strong fit because memory-native products are becoming a real buyer category.", searchTerms: ["ai memory", "meeting memory", "personal memory assistant"] },
    { id: "superwhisper", name: "Superwhisper", vendor: "Superwhisper", logoLetter: "S", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://superwhisper.com/", summary: "A native dictation tool that turns speech into polished text across Mac writing workflows.", categories: ["Writing", "Productivity"], audience: ["Writers", "Founders", "Professionals"], pricing: "Paid", monthlyVisits: 3100000, recommendation: "Worth adding because voice-first writing tools are clearly gaining traction.", searchTerms: ["dictation ai", "voice to text mac", "speech writing assistant"] },
    { id: "grain", name: "Grain", vendor: "Grain", logoLetter: "G", accent: "linear-gradient(145deg, #f97316, #ef4444)", url: "https://grain.com/", summary: "A meeting intelligence platform for recording calls, extracting highlights, and syncing insights into team workflows.", categories: ["Meetings", "Productivity", "Sales"], audience: ["Sales teams", "Customer success", "Managers"], pricing: "Freemium", monthlyVisits: 2500000, recommendation: "A good addition because AI meeting intelligence remains a high-intent software purchase.", searchTerms: ["meeting intelligence", "call recording ai", "sales call notes"] },
    { id: "meetgeek", name: "MeetGeek", vendor: "MeetGeek", logoLetter: "M", accent: "linear-gradient(145deg, #06b6d4, #2563eb)", url: "https://meetgeek.ai/", summary: "An AI meeting assistant that records calls, writes summaries, and tracks follow-ups across teams.", categories: ["Meetings", "Productivity"], audience: ["Managers", "Operators", "Recruiters"], pricing: "Freemium", monthlyVisits: 4400000, recommendation: "A practical meeting layer for users comparing note takers and recap tools.", searchTerms: ["meeting bot ai", "meeting summary assistant", "call recap ai"] },
    { id: "sembly", name: "Sembly AI", vendor: "Sembly", logoLetter: "S", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.sembly.ai/", summary: "An enterprise-friendly meeting assistant focused on call notes, tasks, and team knowledge extraction.", categories: ["Meetings", "Productivity"], audience: ["Enterprises", "Managers", "Operations teams"], pricing: "Freemium", monthlyVisits: 2000000, recommendation: "Useful for buyers who want a more business-oriented meeting AI option.", searchTerms: ["meeting assistant enterprise", "meeting minutes ai", "meeting tasks ai"] },
    { id: "reclaim", name: "Reclaim AI", vendor: "Reclaim", logoLetter: "R", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://reclaim.ai/", summary: "A smart calendar and scheduling platform that protects focus time and automatically reshapes work plans.", categories: ["Productivity", "Automation"], audience: ["Founders", "Teams", "Busy professionals"], pricing: "Free / Paid", monthlyVisits: 6700000, recommendation: "A strong planning product for users who want AI to manage time instead of content.", searchTerms: ["ai calendar", "smart scheduling", "focus time automation"] },
    { id: "sana", name: "Sana", vendor: "Sana", logoLetter: "S", accent: "linear-gradient(145deg, #111827, #ec4899)", url: "https://sana.ai/", summary: "An enterprise AI workspace for search, learning, assistants, and organization-wide knowledge access.", categories: ["Assistants", "Research", "Productivity"], audience: ["Enterprises", "Knowledge teams", "People ops"], pricing: "Paid", monthlyVisits: 4800000, recommendation: "A valuable addition for teams evaluating internal AI workspace platforms.", searchTerms: ["enterprise ai workspace", "company knowledge ai", "internal search ai"] },
    { id: "researchrabbit", name: "ResearchRabbit", vendor: "ResearchRabbit", logoLetter: "R", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://www.researchrabbit.ai/", summary: "A literature discovery tool that maps papers, authors, and citation networks for faster academic research.", categories: ["Research"], audience: ["Researchers", "Students", "PhD teams"], pricing: "Free", monthlyVisits: 2600000, recommendation: "A strong research-specific addition for users exploring beyond general AI chat.", searchTerms: ["paper discovery ai", "citation map", "research graph tool"] },
    { id: "tavily", name: "Tavily", vendor: "Tavily", logoLetter: "T", accent: "linear-gradient(145deg, #14b8a6, #0f766e)", url: "https://www.tavily.com/", summary: "A search API built for AI agents and research systems that need fresh, structured web results.", categories: ["Research", "Coding", "Automation"], audience: ["Developers", "AI engineers", "Agent builders"], pricing: "Usage-based", monthlyVisits: 7300000, recommendation: "Important for builder audiences now wiring live search into agent workflows.", searchTerms: ["ai search api", "agent search", "live web search api"] }
  ]);

  addTools([
    { id: "mem0", name: "Mem0", vendor: "Mem0", logoLetter: "M", accent: "linear-gradient(145deg, #0f172a, #14b8a6)", url: "https://mem0.ai/", summary: "A memory layer for AI applications that helps assistants remember user facts, preferences, and long-term context.", categories: ["Coding", "Automation", "Research"], audience: ["Developers", "AI teams", "Product teams"], pricing: "Usage-based", monthlyVisits: 3000000, recommendation: "A timely addition because memory infrastructure is becoming a core agent building block.", searchTerms: ["ai memory layer", "llm memory", "agent memory api"] },
    { id: "langfuse", name: "Langfuse", vendor: "Langfuse", logoLetter: "L", accent: "linear-gradient(145deg, #f97316, #fb7185)", url: "https://langfuse.com/", summary: "An open-source LLM engineering platform for tracing, evaluations, prompts, and analytics.", categories: ["Coding", "Research", "Automation"], audience: ["AI engineers", "Developers", "Platform teams"], pricing: "Free / Paid", monthlyVisits: 6100000, recommendation: "A core listing for teams moving from prototypes into real LLM operations.", searchTerms: ["llm observability", "prompt analytics", "tracing platform ai"] },
    { id: "coderabbit", name: "CodeRabbit", vendor: "CodeRabbit", logoLetter: "C", accent: "linear-gradient(145deg, #2563eb, #f97316)", url: "https://www.coderabbit.ai/", summary: "An AI code review platform designed to catch issues inside pull requests and accelerate review cycles.", categories: ["Coding", "Productivity"], audience: ["Developers", "Engineering teams", "Reviewers"], pricing: "Paid", monthlyVisits: 8500000, recommendation: "A highly relevant addition because AI code review has become a clear product segment.", searchTerms: ["ai code review", "pull request review ai", "pr assistant"] },
    { id: "cline", name: "Cline", vendor: "Cline", logoLetter: "C", accent: "linear-gradient(145deg, #2563eb, #8b5cf6)", url: "https://cline.bot/", summary: "An open agentic coding assistant for VS Code that can plan, edit files, and use tools in sequence.", categories: ["Coding", "Automation"], audience: ["Developers", "Indie hackers", "Technical founders"], pricing: "Free", monthlyVisits: 5900000, recommendation: "A strong fit because open agentic coding tools now drive a lot of developer attention.", searchTerms: ["agentic coding", "vscode ai agent", "open source coding agent"] },
    { id: "roocode", name: "Roo Code", vendor: "Roo Code", logoLetter: "R", accent: "linear-gradient(145deg, #111827, #2563eb)", url: "https://roocode.com/", summary: "A coding agent experience focused on iterative software tasks, code changes, and developer control.", categories: ["Coding", "Automation"], audience: ["Developers", "Technical teams", "Builders"], pricing: "Free / Paid", monthlyVisits: 7400000, recommendation: "Useful for users comparing the fast-moving crop of autonomous coding assistants.", searchTerms: ["coding agent", "roo code", "software task ai"] },
    { id: "replicate", name: "Replicate", vendor: "Replicate", logoLetter: "R", accent: "linear-gradient(145deg, #0f172a, #ef4444)", url: "https://replicate.com/", summary: "A platform for running, deploying, and integrating AI models through a developer-friendly API.", categories: ["Coding", "Research", "Design"], audience: ["Developers", "Startups", "AI builders"], pricing: "Usage-based", monthlyVisits: 18200000, recommendation: "A major builder destination that clearly belongs in a high-interest AI directory.", searchTerms: ["model api", "run ai models", "replicate ai"] },
    { id: "modal", name: "Modal", vendor: "Modal", logoLetter: "M", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://modal.com/", summary: "A serverless infrastructure platform for shipping GPU jobs, inference, and AI back-end workloads.", categories: ["Coding", "Automation"], audience: ["Developers", "ML engineers", "Startups"], pricing: "Usage-based", monthlyVisits: 7000000, recommendation: "A practical infrastructure entry for users building model-backed products.", searchTerms: ["serverless gpu", "ai infra platform", "inference backend"] },
    { id: "warp", name: "Warp", vendor: "Warp", logoLetter: "W", accent: "linear-gradient(145deg, #8b5cf6, #ec4899)", url: "https://www.warp.dev/", summary: "A modern terminal with AI assistance, workflows, and collaborative command tooling for developers.", categories: ["Coding", "Productivity"], audience: ["Developers", "DevOps teams", "Power users"], pricing: "Free / Paid", monthlyVisits: 21500000, recommendation: "A high-visibility developer product that blends AI into everyday command-line work.", searchTerms: ["ai terminal", "developer terminal ai", "command line assistant"] },
    { id: "julius", name: "Julius AI", vendor: "Julius", logoLetter: "J", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://julius.ai/", summary: "A data analysis assistant that helps users work through spreadsheets, charts, files, and quantitative questions.", categories: ["Research", "Productivity"], audience: ["Analysts", "Students", "Operators"], pricing: "Freemium", monthlyVisits: 11400000, recommendation: "A strong addition because data copilot products are pulling heavy user interest.", searchTerms: ["data analysis ai", "spreadsheet ai", "chart assistant"] },
    { id: "gumloop", name: "Gumloop", vendor: "Gumloop", logoLetter: "G", accent: "linear-gradient(145deg, #0f766e, #14b8a6)", url: "https://www.gumloop.com/", summary: "A visual automation builder for AI workflows, data extraction, and repeated knowledge work.", categories: ["Automation", "Productivity"], audience: ["Operators", "Growth teams", "No-code builders"], pricing: "Freemium", monthlyVisits: 9800000, recommendation: "A hot no-code automation pick for users who want agent-style flows without heavy coding.", searchTerms: ["ai workflow builder", "no code ai automation", "automation canvas ai"] }
  ]);

  addTools([
    { id: "wordware", name: "Wordware", vendor: "Wordware", logoLetter: "W", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.wordware.ai/", summary: "A prompt and agent building environment that makes AI logic feel more like collaborative document editing than code.", categories: ["Coding", "Automation", "Productivity"], audience: ["PMs", "Developers", "AI teams"], pricing: "Freemium", monthlyVisits: 6600000, recommendation: "Useful because builder tools are converging around more accessible AI orchestration interfaces.", searchTerms: ["prompt builder", "agent builder", "ai workflow editor"] },
    { id: "kittl", name: "Kittl", vendor: "Kittl", logoLetter: "K", accent: "linear-gradient(145deg, #111827, #f97316)", url: "https://www.kittl.com/", summary: "A design platform with AI support for graphics, typography, product visuals, and creative production.", categories: ["Design", "Productivity"], audience: ["Designers", "Merch sellers", "Creators"], pricing: "Freemium", monthlyVisits: 12100000, recommendation: "A strong design addition for users beyond generic image generators.", searchTerms: ["graphic design ai", "typography ai", "creative design platform"] },
    { id: "pixelcut", name: "Pixelcut", vendor: "Pixelcut", logoLetter: "P", accent: "linear-gradient(145deg, #ec4899, #f97316)", url: "https://www.pixelcut.ai/", summary: "A product-image and commerce design tool for background cleanup, ad creatives, and catalog visuals.", categories: ["Design", "Sales"], audience: ["E-commerce teams", "Marketers", "Small businesses"], pricing: "Freemium", monthlyVisits: 24800000, recommendation: "A very high-traffic practical design tool that clearly belongs in the directory.", searchTerms: ["product photo ai", "ecommerce creative ai", "background removal design"] },
    { id: "playground", name: "Playground AI", vendor: "Playground", logoLetter: "P", accent: "linear-gradient(145deg, #7c3aed, #ec4899)", url: "https://playground.com/", summary: "A visual creation workspace for generating and editing images with prompt-based and iterative tools.", categories: ["Design"], audience: ["Creators", "Designers", "Social teams"], pricing: "Freemium", monthlyVisits: 19200000, recommendation: "A large-audience image product with steady creative discovery value.", searchTerms: ["image generation workspace", "playground ai", "visual creator ai"] },
    { id: "flair", name: "Flair", vendor: "Flair", logoLetter: "F", accent: "linear-gradient(145deg, #2563eb, #f43f5e)", url: "https://flair.ai/", summary: "An AI product photography tool for branded scenes, catalog visuals, and campaign-style creative.", categories: ["Design", "Sales"], audience: ["E-commerce teams", "Brand teams", "Designers"], pricing: "Paid", monthlyVisits: 3400000, recommendation: "Useful for product marketers who need commerce visuals rather than general art output.", searchTerms: ["product photography ai", "brand visuals ai", "ecommerce scene generator"] },
    { id: "adcreative", name: "AdCreative.ai", vendor: "AdCreative", logoLetter: "A", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://www.adcreative.ai/", summary: "An ad asset platform for generating creatives, copy, and performance-focused campaign variations.", categories: ["Sales", "Design", "Writing"], audience: ["Performance marketers", "Agencies", "SMBs"], pricing: "Paid", monthlyVisits: 5700000, recommendation: "A strong fit because ad generation remains a high-commercial-intent AI use case.", searchTerms: ["ad creative ai", "performance marketing ai", "ad copy generator"] },
    { id: "predis", name: "Predis.ai", vendor: "Predis", logoLetter: "P", accent: "linear-gradient(145deg, #f97316, #fb7185)", url: "https://predis.ai/", summary: "A social content platform for AI-generated posts, carousels, short-form assets, and scheduling help.", categories: ["Sales", "Writing", "Design"], audience: ["Marketers", "Agencies", "Creators"], pricing: "Freemium", monthlyVisits: 8100000, recommendation: "A practical marketing stack addition for teams shipping lots of social content.", searchTerms: ["social media ai", "carousel maker ai", "post generator ai"] },
    { id: "creatify", name: "Creatify", vendor: "Creatify", logoLetter: "C", accent: "linear-gradient(145deg, #06b6d4, #2563eb)", url: "https://creatify.ai/", summary: "A product video generator that turns URLs or catalog data into ad-ready clips and variations.", categories: ["Video", "Sales"], audience: ["Marketers", "E-commerce teams", "Agencies"], pricing: "Freemium", monthlyVisits: 4200000, recommendation: "A useful pick for teams producing AI video ads at scale.", searchTerms: ["product video ai", "ugc ad ai", "video ad generator"] },
    { id: "uizard", name: "Uizard", vendor: "Uizard", logoLetter: "U", accent: "linear-gradient(145deg, #8b5cf6, #2563eb)", url: "https://uizard.io/", summary: "A UI design tool with AI support for wireframes, screens, and fast product ideation.", categories: ["Design", "Productivity"], audience: ["Product teams", "Designers", "Founders"], pricing: "Freemium", monthlyVisits: 9400000, recommendation: "Still a recognizable product-design AI brand with strong discovery value.", searchTerms: ["ui design ai", "wireframe generator", "product mockup ai"] },
    { id: "galileo", name: "Galileo AI", vendor: "Galileo", logoLetter: "G", accent: "linear-gradient(145deg, #111827, #8b5cf6)", url: "https://www.usegalileo.ai/", summary: "A UI generation product for turning prompts and requirements into polished interface concepts.", categories: ["Design"], audience: ["Product designers", "Founders", "Design teams"], pricing: "Paid", monthlyVisits: 5300000, recommendation: "A notable interface-generation product with clear builder appeal.", searchTerms: ["ui generator ai", "interface design ai", "product design assistant"] }
  ]);

  addTools([
    { id: "relume", name: "Relume", vendor: "Relume", logoLetter: "R", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.relume.io/", summary: "A website planning and design system workspace with AI help for site maps, wireframes, and structure.", categories: ["Design", "Productivity"], audience: ["Web designers", "Agencies", "Founders"], pricing: "Freemium", monthlyVisits: 6900000, recommendation: "A strong site-building workflow tool that complements UI-first generators.", searchTerms: ["website wireframe ai", "sitemap ai", "web design system ai"] },
    { id: "dora", name: "Dora", vendor: "Dora", logoLetter: "D", accent: "linear-gradient(145deg, #0f172a, #2563eb)", url: "https://www.dora.run/", summary: "A design and motion site builder that uses AI to accelerate visual website creation.", categories: ["Design", "Coding"], audience: ["Designers", "Creative developers", "Agencies"], pricing: "Freemium", monthlyVisits: 4100000, recommendation: "Useful for users drawn to visually rich site-building workflows.", searchTerms: ["website builder ai", "motion web design", "dora ai"] },
    { id: "mokker", name: "Mokker", vendor: "Mokker", logoLetter: "M", accent: "linear-gradient(145deg, #f97316, #ec4899)", url: "https://mokker.ai/", summary: "A product image generator for packshots, catalog shots, and campaign-style backgrounds.", categories: ["Design", "Sales"], audience: ["E-commerce teams", "Sellers", "Marketers"], pricing: "Freemium", monthlyVisits: 2700000, recommendation: "A commercial design tool with clear product-photo intent.", searchTerms: ["packshot ai", "product photo background ai", "ecommerce images ai"] },
    { id: "udio", name: "Udio", vendor: "Udio", logoLetter: "U", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://www.udio.com/", summary: "A music generation platform for creating songs, vocals, and stylized audio compositions.", categories: ["Audio"], audience: ["Musicians", "Creators", "Producers"], pricing: "Free / Paid", monthlyVisits: 15600000, recommendation: "A high-interest music AI product with major consumer attention.", searchTerms: ["ai music generator", "song generation ai", "audio creation ai"] },
    { id: "stableaudio", name: "Stable Audio", vendor: "Stability AI", logoLetter: "S", accent: "linear-gradient(145deg, #111827, #f97316)", url: "https://www.stableaudio.com/", summary: "A prompt-based audio generation tool for sound design, music, and creative production.", categories: ["Audio"], audience: ["Creators", "Sound designers", "Studios"], pricing: "Freemium", monthlyVisits: 4000000, recommendation: "A solid audio generation addition with strong brand recognition.", searchTerms: ["audio generation ai", "sound design ai", "music prompt tool"] },
    { id: "submagic", name: "Submagic", vendor: "Submagic", logoLetter: "S", accent: "linear-gradient(145deg, #2563eb, #fb7185)", url: "https://www.submagic.co/", summary: "A short-form video editing tool for captions, social clips, and creator-friendly automation.", categories: ["Video", "Writing"], audience: ["Creators", "Agencies", "Social teams"], pricing: "Freemium", monthlyVisits: 13600000, recommendation: "A high-heat creator tool that belongs in the video workflow lane.", searchTerms: ["caption generator ai", "short video editor ai", "social clip captions"] },
    { id: "airops", name: "AirOps", vendor: "AirOps", logoLetter: "A", accent: "linear-gradient(145deg, #2563eb, #0f766e)", url: "https://www.airops.com/", summary: "An AI operations platform for content workflows, SEO programs, and repeatable growth tasks.", categories: ["Automation", "Writing", "Sales"], audience: ["Growth teams", "SEO teams", "Agencies"], pricing: "Paid", monthlyVisits: 3200000, recommendation: "A good fit for the operational side of AI content production.", searchTerms: ["seo workflow ai", "content ops ai", "growth automation ai"] },
    { id: "mailmaestro", name: "MailMaestro", vendor: "Maestro Labs", logoLetter: "M", accent: "linear-gradient(145deg, #14b8a6, #2563eb)", url: "https://www.maestrolabs.com/", summary: "An email productivity assistant that drafts replies, summarizes threads, and helps busy inbox workflows move faster.", categories: ["Writing", "Productivity"], audience: ["Professionals", "Executives", "Sales teams"], pricing: "Freemium", monthlyVisits: 2400000, recommendation: "A focused inbox AI product that complements meeting and calendar tools.", searchTerms: ["email drafting ai", "outlook ai assistant", "gmail ai writing"] },
    { id: "firecrawl", name: "Firecrawl", vendor: "Firecrawl", logoLetter: "F", accent: "linear-gradient(145deg, #f97316, #ef4444)", url: "https://www.firecrawl.dev/", summary: "A web crawling and extraction API for feeding fresh site content into LLM and agent workflows.", categories: ["Coding", "Research", "Automation"], audience: ["Developers", "Agent builders", "Data teams"], pricing: "Usage-based", monthlyVisits: 12900000, recommendation: "A high-heat builder tool because live web data ingestion is now a core agent primitive.", searchTerms: ["web crawl api", "llm scraping api", "site extraction ai"] },
    { id: "fal", name: "fal", vendor: "fal", logoLetter: "F", accent: "linear-gradient(145deg, #111827, #14b8a6)", url: "https://fal.ai/", summary: "A generative media infrastructure platform for fast image and video model inference in production.", categories: ["Coding", "Design", "Video"], audience: ["Developers", "Startups", "Creative engineers"], pricing: "Usage-based", monthlyVisits: 17800000, recommendation: "A major builder platform for shipping media AI features quickly.", searchTerms: ["image model api", "video model inference", "generative media api"] }
  ]);

  addTools([
    { id: "weaviate", name: "Weaviate", vendor: "Weaviate", logoLetter: "W", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://weaviate.io/", summary: "A vector database and AI-native data platform for retrieval, hybrid search, and semantic applications.", categories: ["Coding", "Research"], audience: ["Developers", "AI teams", "Data teams"], pricing: "Free / Paid", monthlyVisits: 4700000, recommendation: "A strong retrieval infrastructure listing for serious builder audiences.", searchTerms: ["vector database", "semantic search ai", "retrieval platform"] },
    { id: "qdrant", name: "Qdrant", vendor: "Qdrant", logoLetter: "Q", accent: "linear-gradient(145deg, #111827, #8b5cf6)", url: "https://qdrant.tech/", summary: "A vector search engine for embeddings, recommendations, and AI-powered retrieval systems.", categories: ["Coding", "Research"], audience: ["Developers", "ML engineers", "Platform teams"], pricing: "Free / Paid", monthlyVisits: 3500000, recommendation: "A useful complement to Pinecone and Weaviate for retrieval buyers.", searchTerms: ["vector search engine", "embedding database", "retrieval engine"] },
    { id: "hume", name: "Hume AI", vendor: "Hume", logoLetter: "H", accent: "linear-gradient(145deg, #ec4899, #8b5cf6)", url: "https://www.hume.ai/", summary: "A voice and emotion AI platform for expressive speech interfaces and conversational experiences.", categories: ["Audio", "Coding", "Assistants"], audience: ["Developers", "Voice teams", "Experience designers"], pricing: "Usage-based", monthlyVisits: 2900000, recommendation: "A compelling voice platform for builders moving beyond basic transcription.", searchTerms: ["emotion ai voice", "expressive speech ai", "voice interface api"] },
    { id: "composio", name: "Composio", vendor: "Composio", logoLetter: "C", accent: "linear-gradient(145deg, #2563eb, #22c55e)", url: "https://composio.dev/", summary: "A tool integration layer that lets AI agents connect to SaaS apps, actions, and business workflows.", categories: ["Automation", "Coding"], audience: ["Developers", "AI teams", "Automation builders"], pricing: "Usage-based", monthlyVisits: 3600000, recommendation: "A strong infrastructure entry because agent-to-tool connectivity is a foundational need.", searchTerms: ["agent tools api", "ai app integrations", "tool calling platform"] },
    { id: "livekit", name: "LiveKit", vendor: "LiveKit", logoLetter: "L", accent: "linear-gradient(145deg, #0f172a, #14b8a6)", url: "https://livekit.com/", summary: "A real-time communication platform now widely used for voice AI, multimodal agents, and streaming applications.", categories: ["Coding", "Audio", "Video"], audience: ["Developers", "Voice teams", "Startups"], pricing: "Usage-based", monthlyVisits: 18600000, recommendation: "A major builder platform as voice and real-time agents continue to surge.", searchTerms: ["real time voice ai", "streaming ai sdk", "voice agent platform"] },
    { id: "ltxstudio", name: "LTX Studio", vendor: "LTX Studio", logoLetter: "L", accent: "linear-gradient(145deg, #7c3aed, #ec4899)", url: "https://ltx.studio/", summary: "A story-first AI filmmaking environment for scenes, shots, character continuity, and video planning.", categories: ["Video", "Design"], audience: ["Creators", "Studios", "Marketers"], pricing: "Freemium", monthlyVisits: 10700000, recommendation: "A notable video-native creative product with strong buzz and visual appeal.", searchTerms: ["ai filmmaking", "storyboard video ai", "scene planning ai"] },
    { id: "arcads", name: "Arcads", vendor: "Arcads", logoLetter: "A", accent: "linear-gradient(145deg, #f97316, #fb7185)", url: "https://www.arcads.ai/", summary: "An AI ad video platform for generating UGC-style clips, variations, and performance creatives.", categories: ["Video", "Sales"], audience: ["Marketers", "Growth teams", "E-commerce teams"], pricing: "Paid", monthlyVisits: 6200000, recommendation: "A hot ad-creative product that belongs in the sales and video lanes.", searchTerms: ["ugc ad ai", "ad video generator", "performance creative ai"] },
    { id: "tavus", name: "Tavus", vendor: "Tavus", logoLetter: "T", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.tavus.io/", summary: "A personalized video and conversational avatar platform for outreach, support, and AI interaction flows.", categories: ["Video", "Sales", "Assistants"], audience: ["Sales teams", "Customer teams", "Developers"], pricing: "Paid", monthlyVisits: 7500000, recommendation: "A strong personalized video product with clear enterprise use cases.", searchTerms: ["personalized video ai", "avatar outreach ai", "video personalization"] },
    { id: "supermaven", name: "Supermaven", vendor: "Supermaven", logoLetter: "S", accent: "linear-gradient(145deg, #2563eb, #f97316)", url: "https://supermaven.com/", summary: "A coding assistant focused on fast autocomplete, large context, and editor-native developer speed.", categories: ["Coding", "Productivity"], audience: ["Developers", "Indie hackers", "Engineering teams"], pricing: "Paid", monthlyVisits: 8900000, recommendation: "A relevant coding product as developers compare fast completion tools with agentic options.", searchTerms: ["code autocomplete ai", "editor coding assistant", "large context coding ai"] },
    { id: "bland", name: "Bland AI", vendor: "Bland", logoLetter: "B", accent: "linear-gradient(145deg, #111827, #ef4444)", url: "https://www.bland.ai/", summary: "A voice agent platform for automated phone calls, outbound workflows, and conversational operations.", categories: ["Audio", "Automation", "Sales"], audience: ["Operations teams", "Support teams", "Sales teams"], pricing: "Usage-based", monthlyVisits: 5200000, recommendation: "A timely voice-agent addition as phone-based AI automation gets real traction.", searchTerms: ["voice agent platform", "ai phone calls", "call automation ai"] }
  ]);
}());
