(function () {
  const catalog = window.AI_CATALOG;
  if (!catalog || !Array.isArray(catalog.tools)) {
    return;
  }

  function formatTrafficLabel(monthlyVisits) {
    if (monthlyVisits >= 1000000000) {
      return `${(monthlyVisits / 1000000000).toFixed(1)}B monthly visits`;
    }
    return `${(monthlyVisits / 1000000).toFixed(1)}M monthly visits`;
  }

  const extraTools = [
    { id: "rytr", name: "Rytr", vendor: "Rytr", logoLetter: "R", accent: "linear-gradient(145deg, #8b5cf6, #2563eb)", url: "https://rytr.me/", summary: "A lightweight AI copy tool for social posts, emails, short-form content, and quick drafting tasks.", categories: ["Writing", "Sales"], audience: ["Small businesses", "Freelancers", "Marketers"], pricing: "Freemium", monthlyVisits: 8700000, recommendation: "Useful for buyers who want a simpler writing product without the overhead of a larger suite.", searchTerms: ["copywriting ai", "rytr me"] },
    { id: "sudowrite", name: "Sudowrite", vendor: "Sudowrite", logoLetter: "S", accent: "linear-gradient(145deg, #7c3aed, #f43f5e)", url: "https://www.sudowrite.com/", summary: "A creative writing tool built for fiction drafting, brainstorming, and narrative expansion.", categories: ["Writing"], audience: ["Authors", "Screenwriters", "Creative writers"], pricing: "Paid", monthlyVisits: 5400000, recommendation: "A notable addition because creative writing buyers have different needs than business-content users.", searchTerms: ["fiction ai", "novel writing ai"] },
    { id: "hyperwrite", name: "HyperWrite", vendor: "HyperWrite", logoLetter: "H", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://hyperwriteai.com/", summary: "A writing and personal productivity assistant for drafting, research, and everyday workflow support.", categories: ["Writing", "Assistants", "Productivity"], audience: ["Students", "Professionals", "Founders"], pricing: "Freemium", monthlyVisits: 6900000, recommendation: "Worth comparing if the buyer wants AI help spread across multiple small tasks through the day.", searchTerms: ["personal productivity ai", "writing browser ai"] },
    { id: "gravitywrite", name: "GravityWrite", vendor: "GravityWrite", logoLetter: "G", accent: "linear-gradient(145deg, #0f172a, #2563eb)", url: "https://gravitywrite.com/", summary: "An AI content platform aimed at blogs, social copy, and business writing templates.", categories: ["Writing", "Sales"], audience: ["Marketers", "Agencies", "Small businesses"], pricing: "Freemium", monthlyVisits: 5100000, recommendation: "A useful addition for template-driven content production and budget-conscious marketing teams.", searchTerms: ["content generator ai", "blog writer ai"] },
    { id: "simplified", name: "Simplified", vendor: "Simplified", logoLetter: "S", accent: "linear-gradient(145deg, #ec4899, #f97316)", url: "https://simplified.com/", summary: "A broad marketing suite combining AI writing, design, social publishing, and content collaboration.", categories: ["Writing", "Design", "Sales"], audience: ["Marketing teams", "Agencies", "Creators"], pricing: "Freemium", monthlyVisits: 12400000, recommendation: "A strong suite-style option when a team wants multiple marketing jobs handled in one place.", searchTerms: ["marketing suite ai", "social media ai"] },
    { id: "anyword", name: "Anyword", vendor: "Anyword", logoLetter: "A", accent: "linear-gradient(145deg, #2563eb, #0f172a)", url: "https://anyword.com/", summary: "A performance marketing copy platform focused on ads, landing pages, and conversion-oriented messaging.", categories: ["Writing", "Sales"], audience: ["Growth teams", "Performance marketers", "Agencies"], pricing: "Paid", monthlyVisits: 6500000, recommendation: "A credible entry when the buyer cares about paid acquisition copy more than general content drafting.", searchTerms: ["ad copy ai", "conversion copy ai"] },
    { id: "surferai", name: "Surfer AI", vendor: "Surfer", logoLetter: "S", accent: "linear-gradient(145deg, #0ea5e9, #2563eb)", url: "https://surferseo.com/ai/", summary: "An SEO writing workflow built around content optimization, SERP structure, and editorial planning.", categories: ["Writing", "Research", "Sales"], audience: ["SEO teams", "Publishers", "Agencies"], pricing: "Paid", monthlyVisits: 9800000, recommendation: "A must-compare listing for search-led content teams and agency SEO workflows.", searchTerms: ["seo ai", "content optimization ai", "serp ai"] },
    { id: "scalenut", name: "Scalenut", vendor: "Scalenut", logoLetter: "S", accent: "linear-gradient(145deg, #22c55e, #16a34a)", url: "https://www.scalenut.com/", summary: "An SEO content platform for briefs, optimization, and AI-assisted publishing workflows.", categories: ["Writing", "Research", "Sales"], audience: ["SEO teams", "Marketers", "Agencies"], pricing: "Paid", monthlyVisits: 4300000, recommendation: "Useful when a team wants strategy plus optimization, not only raw generation.", searchTerms: ["seo content ai", "content brief ai"] },
    { id: "neuronwriter", name: "NeuronWriter", vendor: "NeuronWriter", logoLetter: "N", accent: "linear-gradient(145deg, #1d4ed8, #22c55e)", url: "https://neuronwriter.com/", summary: "An AI SEO writing tool focused on SERP analysis, article optimization, and publishing support.", categories: ["Writing", "Research"], audience: ["SEO specialists", "Publishers", "Agencies"], pricing: "Paid", monthlyVisits: 3600000, recommendation: "A useful listing for buyers who evaluate AI content tools primarily through SEO workflow fit.", searchTerms: ["neuron writer", "seo article ai"] },
    { id: "originalityai", name: "Originality.ai", vendor: "Originality.ai", logoLetter: "O", accent: "linear-gradient(145deg, #111827, #ef4444)", url: "https://originality.ai/", summary: "A content QA product covering plagiarism checks, AI text detection, and publishing review workflows.", categories: ["Writing", "Productivity"], audience: ["Publishers", "Agencies", "Editorial teams"], pricing: "Paid", monthlyVisits: 6100000, recommendation: "Important for teams that care about validation, editorial governance, and content review risk.", searchTerms: ["ai detector", "plagiarism ai", "content qa"] },
    { id: "undetectableai", name: "Undetectable AI", vendor: "Undetectable AI", logoLetter: "U", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://undetectable.ai/", summary: "A rewriting product focused on making AI-generated text read more naturally for human audiences.", categories: ["Writing"], audience: ["Students", "Writers", "Content teams"], pricing: "Paid", monthlyVisits: 10900000, recommendation: "Included because many buyers explicitly shop for humanization and rewrite-focused utilities.", searchTerms: ["humanize ai", "rewrite ai text"] },
    { id: "humata", name: "Humata", vendor: "Humata", logoLetter: "H", accent: "linear-gradient(145deg, #0ea5e9, #14b8a6)", url: "https://www.humata.ai/", summary: "A document Q&A tool designed to let users ask questions against PDFs and uploaded knowledge files.", categories: ["Research", "Productivity"], audience: ["Analysts", "Researchers", "Students"], pricing: "Freemium", monthlyVisits: 9500000, recommendation: "A straightforward addition for users whose real need is faster PDF extraction and document chat.", searchTerms: ["chat with pdf", "document qa", "pdf ai"] },
    { id: "askyourpdf", name: "AskYourPDF", vendor: "AskYourPDF", logoLetter: "A", accent: "linear-gradient(145deg, #7c3aed, #2563eb)", url: "https://askyourpdf.com/", summary: "A PDF chat and document assistant for extracting answers, summaries, and key details from files.", categories: ["Research", "Productivity"], audience: ["Students", "Researchers", "Knowledge workers"], pricing: "Freemium", monthlyVisits: 12100000, recommendation: "Useful because document chat remains one of the clearest intent-driven AI tool categories.", searchTerms: ["pdf chat", "document chat ai"] },
    { id: "chatpdf", name: "ChatPDF", vendor: "ChatPDF", logoLetter: "C", accent: "linear-gradient(145deg, #14b8a6, #0ea5e9)", url: "https://www.chatpdf.com/", summary: "A lightweight chat interface for understanding PDFs, research papers, and long uploaded files.", categories: ["Research", "Productivity"], audience: ["Students", "Researchers", "Consultants"], pricing: "Freemium", monthlyVisits: 15500000, recommendation: "A strong category staple because many users search directly for PDF-specific AI help.", searchTerms: ["chat with pdf", "pdf summarizer"] },
    { id: "pdfgear", name: "PDFgear", vendor: "PDFgear", logoLetter: "P", accent: "linear-gradient(145deg, #2563eb, #06b6d4)", url: "https://www.pdfgear.com/", summary: "A PDF utility suite that adds AI assistance to mainstream editing, conversion, and document workflows.", categories: ["Productivity", "Research"], audience: ["Office teams", "Students", "Professionals"], pricing: "Free / Paid", monthlyVisits: 8600000, recommendation: "Useful where buyers want practical PDF tooling plus a light AI layer rather than chat alone.", searchTerms: ["pdf editor ai", "pdf toolkit"] },
    { id: "updfai", name: "UPDF AI", vendor: "UPDF", logoLetter: "U", accent: "linear-gradient(145deg, #7c3aed, #ec4899)", url: "https://updf.com/chat-pdf/", summary: "An AI-powered PDF assistant connected to broader editing, annotation, and office workflows.", categories: ["Productivity", "Research"], audience: ["Office teams", "Students", "Legal users"], pricing: "Freemium", monthlyVisits: 7700000, recommendation: "A practical inclusion because many users compare PDF chat as part of a full document suite purchase.", searchTerms: ["updf ai", "pdf ai assistant"] },
    { id: "smallpdfai", name: "Smallpdf AI", vendor: "Smallpdf", logoLetter: "S", accent: "linear-gradient(145deg, #ef4444, #f97316)", url: "https://smallpdf.com/ai-pdf", summary: "AI assistance inside Smallpdf's mainstream document toolkit for PDF workflows and file transformation.", categories: ["Productivity", "Research"], audience: ["Professionals", "Students", "Office teams"], pricing: "Freemium", monthlyVisits: 16300000, recommendation: "Good for buyers who already trust a mainstream PDF utility brand and want AI added on.", searchTerms: ["smallpdf ai", "pdf toolkit ai"] },
    { id: "lightpdfai", name: "LightPDF", vendor: "LightPDF", logoLetter: "L", accent: "linear-gradient(145deg, #0ea5e9, #2563eb)", url: "https://lightpdf.com/", summary: "A document utility platform with AI chat, OCR, conversion, and PDF handling features.", categories: ["Productivity", "Research"], audience: ["Students", "Professionals", "Office teams"], pricing: "Freemium", monthlyVisits: 5800000, recommendation: "A useful long-tail listing for practical document buyers comparing all-in-one PDF utilities.", searchTerms: ["light pdf ai", "ocr ai pdf"] },
    { id: "notta", name: "Notta", vendor: "Notta", logoLetter: "N", accent: "linear-gradient(145deg, #2563eb, #14b8a6)", url: "https://www.notta.ai/", summary: "A transcription and meeting capture product for notes, summaries, and audio-to-text workflows.", categories: ["Meetings", "Audio", "Productivity"], audience: ["Operations teams", "Sales teams", "Students"], pricing: "Freemium", monthlyVisits: 9100000, recommendation: "A solid listing because transcription buyers often compare several narrower products before choosing.", searchTerms: ["transcription ai", "meeting notes ai"] },
    { id: "krisp", name: "Krisp", vendor: "Krisp", logoLetter: "K", accent: "linear-gradient(145deg, #2563eb, #7c3aed)", url: "https://krisp.ai/", summary: "A call-quality tool known for noise cancellation, transcripts, and meeting AI utilities.", categories: ["Meetings", "Audio", "Productivity"], audience: ["Remote teams", "Support teams", "Sales teams"], pricing: "Freemium", monthlyVisits: 14700000, recommendation: "A production-grade option when audio quality and call clarity matter more than flashy generation features.", searchTerms: ["noise cancellation ai", "meeting ai", "call audio ai"] },
    { id: "fathom", name: "Fathom", vendor: "Fathom", logoLetter: "F", accent: "linear-gradient(145deg, #0f172a, #06b6d4)", url: "https://www.fathom.ai/", summary: "A meeting assistant for recordings, notes, summaries, and CRM-friendly conversation capture.", categories: ["Meetings", "Sales", "Productivity"], audience: ["Sales teams", "Customer success", "Operations teams"], pricing: "Freemium", monthlyVisits: 8300000, recommendation: "A very practical fit for teams optimizing meeting follow-up and knowledge capture.", searchTerms: ["meeting recorder ai", "sales call ai"] },
    { id: "gong", name: "Gong", vendor: "Gong", logoLetter: "G", accent: "linear-gradient(145deg, #f97316, #ef4444)", url: "https://www.gong.io/", summary: "A revenue intelligence platform using AI to analyze calls, pipeline motion, and sales execution.", categories: ["Sales", "Meetings", "Productivity"], audience: ["Sales leaders", "Revenue teams", "Customer success"], pricing: "Paid", monthlyVisits: 8900000, recommendation: "An important inclusion for serious enterprise GTM buyers comparing AI-enabled revenue platforms.", searchTerms: ["revenue intelligence", "sales ai", "call analysis"] },
    { id: "clay", name: "Clay", vendor: "Clay", logoLetter: "C", accent: "linear-gradient(145deg, #0f172a, #22c55e)", url: "https://www.clay.com/", summary: "A data enrichment and outbound workflow platform popular with modern GTM and prospecting teams.", categories: ["Sales", "Automation", "Research"], audience: ["GTM teams", "Agencies", "Outbound operators"], pricing: "Paid", monthlyVisits: 8200000, recommendation: "High-signal for advanced outbound operators who need more than a generic writing assistant.", searchTerms: ["lead enrichment ai", "outbound ai", "gtm workflow"] },
    { id: "apollo", name: "Apollo", vendor: "Apollo", logoLetter: "A", accent: "linear-gradient(145deg, #2563eb, #0f172a)", url: "https://www.apollo.io/", summary: "A sales engagement and prospecting platform that increasingly layers AI into GTM workflows.", categories: ["Sales", "Automation"], audience: ["Sales teams", "Startups", "Agencies"], pricing: "Freemium", monthlyVisits: 33500000, recommendation: "Included because real buyers often compare AI features inside existing prospecting suites, not only standalone tools.", searchTerms: ["sales prospecting ai", "lead generation ai"] },
    { id: "instantly", name: "Instantly", vendor: "Instantly", logoLetter: "I", accent: "linear-gradient(145deg, #0ea5e9, #14b8a6)", url: "https://instantly.ai/", summary: "An outreach platform for cold email, lead workflows, and AI-assisted outbound operations.", categories: ["Sales", "Automation", "Writing"], audience: ["Outbound teams", "Agencies", "Founders"], pricing: "Paid", monthlyVisits: 11300000, recommendation: "A solid addition for users evaluating AI through the lens of outbound execution and pipeline creation.", searchTerms: ["cold email ai", "outreach ai", "instantly ai"] }
  ].map((tool) => ({
    ...tool,
    trafficLabel: formatTrafficLabel(tool.monthlyVisits),
    sources: {
      futurepedia: "https://www.futurepedia.io/ai-tools",
      toolify: "https://www.toolify.ai/Best-trending-AI-Tools"
    }
  }));

  const existingIds = new Set(catalog.tools.map((tool) => tool.id));
  extraTools.forEach((tool) => {
    if (!existingIds.has(tool.id)) {
      catalog.tools.push(tool);
      existingIds.add(tool.id);
    }
  });
}());
